* 6809 assembly program generated by cmoc 0.1.86


	SECTION	code


_hof_index	EXPORT


*******************************************************************************

* FUNCTION hof_index(): defined at core/hof.c:5
_hof_index	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
* Formal parameter(s):
*      5,U:    1 byte : level: unsigned char: line 5
*      7,U:    1 byte : place: unsigned char: line 5
* Line core/hof.c:7: return with value
	LDB	5,U		variable level
	ADDB	#$FF		255
	PSHS	B
	LDA	7,U
	LDB	#$05
	MUL			result of type byte in B
	ADDB	,S+
* optim: branchToNextLocation
* Useless label L00006 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION hof_index(): defined at core/hof.c:5
funcend_hof_index	EQU *
funcsize_hof_index	EQU	funcend_hof_index-_hof_index
_hof_clear	EXPORT


*******************************************************************************

* FUNCTION hof_clear(): defined at core/hof.c:10
_hof_clear	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-2,S
* Formal parameter(s):
*      4,U:    2 bytes: tbl: struct AnonStruct_core/hof.h:45 *: line 10
* Local non-static variable(s):
*     -2,U:    1 byte : i: unsigned char: line 11
*     -1,U:    1 byte : j: unsigned char: line 11
* Line core/hof.c:12: for init
* Line core/hof.c:12: assignment: =
	CLRB
	STB	-2,U		variable i
	LBRA	L00014		jump to for condition
L00013	EQU	*
* Line core/hof.c:12: for body
* Line core/hof.c:13: for init
* Line core/hof.c:13: assignment: =
	CLRB
	STB	-1,U		variable j
	BRA	L00018		jump to for condition
L00017	EQU	*
* Line core/hof.c:13: for body
* Line core/hof.c:13: assignment: =
* LDB #$2E optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-1,U		variable j
	CLRA			extend byte index expression
	PSHS	B,A		preserve array index
	LDB	-2,U		variable i
* optim: stripExtraClrA_B
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	4,U		pointer tbl
	LEAX	D,X		add offset
	LEAX	,X		member name of AnonStruct_core/hof.h:45
	TFR	X,D
	ADDD	,S++		add stacked array index to array address in D
	TFR	D,X		put resulting address in X
	LDB	#46		optim: optimizeStackOperations1
	STB	,X
* Useless label L00019 removed
* Line core/hof.c:13: for increment(s)
	INC	-1,U
L00018	EQU	*
* Line core/hof.c:13: for condition
	LDB	-1,U		variable j
	CMPB	#$19
	BLO	L00017
* optim: branchToNextLocation
* Useless label L00020 removed
* Line core/hof.c:14: assignment: =
* CLRB  optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-2,U		variable i
* optim: stripOpToDeadReg
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	4,U		pointer tbl
	LEAX	D,X		add offset
	LEAX	,X		member name of AnonStruct_core/hof.h:45
	TFR	X,D
* optim: stripConsecOppositeTFRs
* optim: optimizeLeax
	LDB	#0		optim: optimizeStackOperations1
	STB	25,X		optim: optimizeLeax
* Line core/hof.c:15: assignment: =
	CLRA
* optim: removeClr
	PSHS	B,A
	LDB	-2,U		variable i
* optim: stripExtraClrA_B
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	4,U		pointer tbl
	LEAX	D,X		add offset
* optim: optimizeLeax
	PULS	A,B		retrieve value to store
	STD	26,X		optim: optimizeLeax
* Useless label L00015 removed
* Line core/hof.c:12: for increment(s)
	INC	-2,U
L00014	EQU	*
* Line core/hof.c:12: for condition
	LDB	-2,U		variable i
	CMPB	#$0A
	LBLO	L00013
* optim: branchToNextLocation
* Useless label L00016 removed
* Useless label L00007 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION hof_clear(): defined at core/hof.c:10
funcend_hof_clear	EQU *
funcsize_hof_clear	EQU	funcend_hof_clear-_hof_clear


*******************************************************************************

* FUNCTION read_num(): defined at core/hof.c:22
_read_num	EQU	*
.static.function.read_num	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-6,S
* Formal parameter(s):
*      4,U:    2 bytes: buf: const unsigned char *: line 22
*      6,U:    2 bytes: len: unsigned int: line 22
*      8,U:    2 bytes: pos: unsigned int *: line 22
*     10,U:    2 bytes: ok: unsigned char *: line 23
* Local non-static variable(s):
*     -6,U:    2 bytes: v: int: line 24
*     -4,U:    1 byte : neg: unsigned char: line 25
*     -3,U:    1 byte : digits: unsigned char: line 25
*     -2,U:    2 bytes: p: unsigned int: line 26
* Line core/hof.c:24: init of variable v
	CLRA
	CLRB
	STD	-6,U		variable v
* Line core/hof.c:25: init of variable neg
	CLR	-4,U		variable neg
* Line core/hof.c:25: init of variable digits
	CLR	-3,U		variable digits
* Line core/hof.c:26: init of variable p
	LDD	[8,U]		indirection
	STD	-2,U		variable p
* Line core/hof.c:28: if
* optim: storeLoad
	CMPD	6,U		variable len
	BHS	L00026		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00023 removed
	LDB	#$2D		decimal 45 signed
	SEX			promotion of binary operand
	PSHS	B,A
	LDD	-2,U		variable p
	LDX	4,U		pointer buf
* optimizeLoadDX
	LDB	D,X		get r-value
	CLRA			promotion of binary operand
	CMPD	,S++
	BNE	L00026		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00021 removed
* Line core/hof.c:28
* Line core/hof.c:28: assignment: =
	LDB	#$01
	STB	-4,U		variable neg
* Line core/hof.c:28: post-increment
	LDX	-2,U		variable `p', declared at core/hof.c:28
	LEAX	1,X
	STX	-2,U
* Useless label L00022 removed
* Useless label L00024 removed
* Line core/hof.c:29: while
	BRA	L00026		jump to while condition
L00025	EQU	*		while body
* Line core/hof.c:30: assignment: =
	LDB	#$30		decimal 48 signed
	PSHS	B
	LDD	-2,U		variable p
	LDX	4,U		pointer buf
	LEAX	D,X		add offset
	LDB	,X		get r-value
	SUBB	,S+
	CLRA			promotion of binary operand
	PSHS	B,A
	LDD	-6,U		variable `v', declared at core/hof.c:24
	LBSR	MUL16BY10
	ADDD	,S++
	STD	-6,U
* Line core/hof.c:31: post-increment
	LDX	-2,U		variable `p', declared at core/hof.c:31
	LEAX	1,X
	STX	-2,U
* Line core/hof.c:31: post-increment
	INC	-3,U
L00026	EQU	*		while condition at core/hof.c:29
	LDD	-2,U		variable p
	CMPD	6,U		variable len
	BHS	L00027		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00029 removed
	LDB	#$30		decimal 48 signed
	SEX			promotion of binary operand
	PSHS	B,A
	LDD	-2,U		variable p
	LDX	4,U		pointer buf
* optimizeLoadDX
	LDB	D,X		get r-value
	CLRA			promotion of binary operand
	CMPD	,S++
	BLO	L00027		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00028 removed
	LDB	#$39		decimal 57 signed
	SEX			promotion of binary operand
	PSHS	B,A
	LDD	-2,U		variable p
	LDX	4,U		pointer buf
* optimizeLoadDX
	LDB	D,X		get r-value
	CLRA			promotion of binary operand
	CMPD	,S++
	LBLS	L00025
* optim: branchToNextLocation
L00027	EQU	*		after end of while starting at core/hof.c:29
* Line core/hof.c:33: if
	LDB	-3,U		variable `digits', declared at core/hof.c:25
* optim: loadCmpZeroBeqOrBne
	BNE	L00031
* optim: branchToNextLocation
* Useless label L00030 removed
* Line core/hof.c:33
* Line core/hof.c:33: assignment: =
	CLRA
* CLRB  optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
* optim: optimizeLdx
	LDB	#0		optim: optimizeStackOperations1
	STB	[10,U]		optim: optimizeLdx
L00031	EQU	*		else clause of if() started at core/hof.c:33
* Useless label L00032 removed
* Line core/hof.c:34: if
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	-2,U		variable p
	ADDD	#$01		1
	CMPD	6,U		optim: optimizeStackOperations4
	BHS	L00033
* optim: branchToNextLocation
* Useless label L00036 removed
	LDB	#$0D		decimal 13 signed
	SEX			promotion of binary operand
	PSHS	B,A
	LDD	-2,U		variable p
	LDX	4,U		pointer buf
* optimizeLoadDX
	LDB	D,X		get r-value
	CLRA			promotion of binary operand
	CMPD	,S++
	BNE	L00033
* optim: branchToNextLocation
* Useless label L00035 removed
	LDB	#$0A		decimal 10 signed
	SEX			promotion of binary operand
	PSHS	B,A
	LDD	-2,U		variable p
	ADDD	#$01		1
	LDX	4,U		pointer buf
* optimizeLoadDX
	LDB	D,X		get r-value
	CLRA			promotion of binary operand
	CMPD	,S++
	BEQ	L00034		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
L00033	EQU	*		then clause of if() started at core/hof.c:34
* Line core/hof.c:34
* Line core/hof.c:34: assignment: =
	CLRA
* CLRB  optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
* optim: optimizeLdx
	LDB	#0		optim: optimizeStackOperations1
	STB	[10,U]		optim: optimizeLdx
L00034	EQU	*		else clause of if() started at core/hof.c:34
* Useless label L00037 removed
* Line core/hof.c:35: assignment: =
	LDD	-2,U		variable p
	ADDD	#$02		2
* optim: stripUselessPushPull
* optim: optimizeLdx
* optim: stripUselessPushPull
	STD	[8,U]		optim: optimizeLdx
* Line core/hof.c:36: return with value
* Line core/hof.c:36: conditional expression
	LDB	-4,U		variable `neg', declared at core/hof.c:25
* optim: loadCmpZeroBeqOrBne
	BEQ	L00039		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00038 removed
	CLRA			Negation of variable v
	CLRB
	SUBD	-6,U
	BRA	L00008		end of true expression of conditional
L00039	EQU	*
	LDD	-6,U		variable `v', declared at core/hof.c:24
* Useless label L00040 removed
* optim: branchToNextLocation
L00008	EQU	*		end of read_num()
	LEAS	,U
	PULS	U,PC
* END FUNCTION read_num(): defined at core/hof.c:22
funcend_read_num	EQU *
funcsize_read_num	EQU	funcend_read_num-_read_num
_hof_parse	EXPORT


*******************************************************************************

* FUNCTION hof_parse(): defined at core/hof.c:39
_hof_parse	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-5,S
* Formal parameter(s):
*      4,U:    2 bytes: buf: const unsigned char *: line 39
*      6,U:    2 bytes: len: unsigned int: line 39
*      8,U:    2 bytes: out: struct AnonStruct_core/hof.h:45 *: line 39
* Local non-static variable(s):
*     -5,U:    2 bytes: pos: unsigned int: line 40
*     -3,U:    1 byte : i: unsigned char: line 41
*     -2,U:    1 byte : j: unsigned char: line 41
*     -1,U:    1 byte : ok: unsigned char: line 41
* Line core/hof.c:40: init of variable pos
	CLRA
	CLRB
	STD	-5,U		variable pos
* Line core/hof.c:41: init of variable ok
	LDB	#$01		1
	STB	-1,U		variable ok
* Line core/hof.c:43: function call: hof_clear()
	LDD	8,U		variable `out', declared at core/hof.c:39
	PSHS	B,A		argument 1 of hof_clear(): struct AnonStruct_core/hof.h:45 *
	LBSR	_hof_clear
	LEAS	2,S
* Line core/hof.c:45: for init
* Line core/hof.c:45: assignment: =
	CLRB
	STB	-3,U		variable i
	LBRA	L00042		jump to for condition
L00041	EQU	*
* Line core/hof.c:45: for body
* Line core/hof.c:46: if
* optim: optimize16BitStackOps1
* optim: optimize16BitStackOps1
* optim: stripOpToDeadReg
* optim: stripOpToDeadReg
* PSHS B,A optim: optimizeStackOperations1
	LDD	-5,U		variable pos
* optim: combineConsecutiveOps
	ADDD	#$1B		optim: combineConsecutiveOps
	CMPD	6,U		optim: optimize16BitStackOps1
	BLS	L00046		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00045 removed
* Line core/hof.c:46
* Line core/hof.c:46: assignment: =
	CLR	-1,U		variable ok
	LBRA	L00044		break
L00046	EQU	*		else clause of if() started at core/hof.c:46
* Useless label L00047 removed
* Line core/hof.c:47: for init
* Line core/hof.c:47: assignment: =
	CLRB
	STB	-2,U		variable j
	BRA	L00049		jump to for condition
L00048	EQU	*
* Line core/hof.c:47: for body
* Line core/hof.c:47: assignment: =
	LDB	-2,U		variable `j', declared at core/hof.c:41
	CLRA			promotion of binary operand
	ADDD	-5,U		optim: pushDLoadAdd
* 
* 
	LDX	4,U		pointer buf
* optimizeLoadDX
	LDB	D,X		get r-value
* Cast from `const unsigned char' to byte: result already in B
	PSHS	B
	LDB	-2,U		variable j
	CLRA			extend byte index expression
	PSHS	B,A		preserve array index
	LDB	-3,U		variable i
* optim: stripExtraClrA_B
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	8,U		pointer out
	LEAX	D,X		add offset
	LEAX	,X		member name of AnonStruct_core/hof.h:45
	TFR	X,D
	ADDD	,S++		add stacked array index to array address in D
	TFR	D,X		put resulting address in X
	LDB	,S+
	STB	,X
* Useless label L00050 removed
* Line core/hof.c:47: for increment(s)
	INC	-2,U
L00049	EQU	*
* Line core/hof.c:47: for condition
	LDB	-2,U		variable j
	CMPB	#$19
	BLO	L00048
* optim: branchToNextLocation
* Useless label L00051 removed
* Line core/hof.c:48: assignment: =
	CLRB
	PSHS	B
	LDB	-3,U		variable i
* optim: stripOpToDeadReg
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	8,U		pointer out
	LEAX	D,X		add offset
	LEAX	,X		member name of AnonStruct_core/hof.h:45
	TFR	X,D
* optim: stripConsecOppositeTFRs
* optim: optimizeLeax
	LDB	,S+
	STB	25,X		optim: optimizeLeax
* Line core/hof.c:49: assignment: =
	LDD	-5,U		variable pos
	ADDD	#$19		25
	STD	-5,U
* Line core/hof.c:50: if
	LDB	#$0D		decimal 13 signed
	SEX			promotion of binary operand
	PSHS	B,A
	LDD	-5,U		variable pos
	LDX	4,U		pointer buf
* optimizeLoadDX
	LDB	D,X		get r-value
	CLRA			promotion of binary operand
	CMPD	,S++
	BNE	L00052
* optim: branchToNextLocation
* Useless label L00054 removed
	LDB	#$0A		decimal 10 signed
	SEX			promotion of binary operand
	PSHS	B,A
	LDD	-5,U		variable pos
	ADDD	#$01		1
	LDX	4,U		pointer buf
* optimizeLoadDX
	LDB	D,X		get r-value
	CLRA			promotion of binary operand
	CMPD	,S++
	BEQ	L00053		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
L00052	EQU	*		then clause of if() started at core/hof.c:50
* Line core/hof.c:50
* Line core/hof.c:50: assignment: =
	CLR	-1,U		variable ok
	BRA	L00044		break
L00053	EQU	*		else clause of if() started at core/hof.c:50
* Useless label L00055 removed
* Line core/hof.c:51: assignment: =
	LDD	-5,U		variable pos
	ADDD	#$02		2
	STD	-5,U
* Line core/hof.c:52: assignment: =
* Line core/hof.c:52: function call: read_num()
	LEAY	-1,U		optim: transformPshsXPshsX
* optim: optimizePshsOps
	LEAX	-5,U		variable `pos', declared at core/hof.c:40
* optim: optimizePshsOps
	LDD	6,U		variable `len', declared at core/hof.c:39
	PSHS	Y,X,B,A		optim: optimizePshsOps
	LDD	4,U		variable `buf', declared at core/hof.c:39
	PSHS	B,A		argument 1 of read_num(): const unsigned char *
	LBSR	_read_num
	LEAS	8,S
	PSHS	B,A
	LDB	-3,U		variable i
* optim: stripOpToDeadReg
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	8,U		pointer out
	LEAX	D,X		add offset
* optim: optimizeLeax
	PULS	A,B		retrieve value to store
	STD	26,X		optim: optimizeLeax
* Useless label L00043 removed
* Line core/hof.c:45: for increment(s)
	INC	-3,U
L00042	EQU	*
* Line core/hof.c:45: for condition
	LDB	-3,U		variable i
	CMPB	#$0A
	BHS	L00044		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00056 removed
	LDB	-1,U		variable `ok', declared at core/hof.c:41
* optim: loadCmpZeroBeqOrBne
	LBNE	L00041
* optim: branchToNextLocation
L00044	EQU	*		end for
* Line core/hof.c:55: if
	LDB	-1,U		variable `ok', declared at core/hof.c:41
* optim: loadCmpZeroBeqOrBne
	BNE	L00058
* optim: branchToNextLocation
* Useless label L00057 removed
* Line core/hof.c:55
* Line core/hof.c:55: function call: hof_clear()
	LDD	8,U		variable `out', declared at core/hof.c:39
	PSHS	B,A		argument 1 of hof_clear(): struct AnonStruct_core/hof.h:45 *
	LBSR	_hof_clear
	LEAS	2,S
L00058	EQU	*		else clause of if() started at core/hof.c:55
* Useless label L00059 removed
* Line core/hof.c:56: return with value
	LDB	-1,U		variable `ok', declared at core/hof.c:41
* optim: branchToNextLocation
* Useless label L00009 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION hof_parse(): defined at core/hof.c:39
funcend_hof_parse	EQU *
funcsize_hof_parse	EQU	funcend_hof_parse-_hof_parse


*******************************************************************************

* FUNCTION put_num(): defined at core/hof.c:59
_put_num	EQU	*
.static.function.put_num	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-9,S
* Formal parameter(s):
*      4,U:    2 bytes: buf: unsigned char *: line 59
*      6,U:    2 bytes: pos: unsigned int: line 59
*      8,U:    2 bytes: v: int: line 59
* Local non-static variable(s):
*     -9,U:    6 bytes: digits: unsigned char[]: line 60
*     -3,U:    1 byte : n: unsigned char: line 61
*     -2,U:    2 bytes: mag: unsigned int: line 62
* Line core/hof.c:61: init of variable n
	CLR	-3,U		variable n
* Line core/hof.c:64: if
	LDD	8,U		variable v
	ADDD	#0
	BGE	L00061		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00060 removed
* Line core/hof.c:64
* Line core/hof.c:64: assignment: =
* LDB #$2D optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDD	6,U		variable `pos', declared at core/hof.c:64
	ADDD	#1
	STD	6,U
	SUBD	#1		post increment yields initial value
	LDX	4,U		pointer buf
	LEAX	D,X		add offset
	LDB	#45		optim: optimizeStackOperations1
	STB	,X
* Line core/hof.c:64: assignment: =
* optim: optimize16BitStackOps1
* Emitted no code to cast `int' to `unsigned int'
* optim: optimize16BitStackOps1
	CLRA
	CLRB
	SUBD	8,U		optim: optimize16BitStackOps1
	STD	-2,U
	BRA	L00062		jump over else clause
L00061	EQU	*		else clause of if() started at core/hof.c:64
* Line core/hof.c:65
* Line core/hof.c:65: assignment: =
	LDD	8,U		variable `v', declared at core/hof.c:59
* Emitted no code to cast `int' to `unsigned int'
	STD	-2,U
L00062	EQU	*		end of if() started at core/hof.c:64
* Line core/hof.c:67: do-while
L00063	EQU	*		do-while body
* Line core/hof.c:67: assignment: =
	LDX	-2,U		left
	CLRA
	LDB	#$0A		right
	LBSR	DIV16
	PSHS	B,A
	LDB	#$30		decimal 48 signed
	SEX			promotion of binary operand
	ADDD	,S++
* Cast from `unsigned int' to byte: result already in B
	PSHS	B
	LDB	-3,U
	INC	-3,U
	LEAX	-9,U		address of array digits
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Line core/hof.c:67: assignment: /=
	LEAX	-2,U		variable `mag', declared at core/hof.c:62
	PSHS	X		preserve address of left side of assignment
	CLRA
	LDB	#$0A		decimal 10 signed
	LDX	[,S]		get value of left side of assignment
	LBSR	DIV16
	TFR	X,D		quotient to D
	STD	[,S]		store quotient at address of left side of assignment
	LEAS	2,S		dispose of address of left side of assignment
* Useless label L00064 removed
	LDD	-2,U		variable `mag', declared at core/hof.c:62
* optim: loadCmpZeroBeqOrBne
	BNE	L00063
* optim: branchToNextLocation
* Useless label L00065 removed
* Line core/hof.c:68: while
	BRA	L00067		jump to while condition
L00066	EQU	*		while body
* Line core/hof.c:68: assignment: =
	DEC	-3,U
	LDB	-3,U
	LEAX	-9,U		address of array digits
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	PSHS	B
	LDD	6,U		variable `pos', declared at core/hof.c:68
	ADDD	#1
	STD	6,U
	SUBD	#1		post increment yields initial value
	LDX	4,U		pointer buf
	LEAX	D,X		add offset
	LDB	,S+
	STB	,X
L00067	EQU	*		while condition at core/hof.c:68
	LDB	-3,U		variable `n', declared at core/hof.c:61
* optim: loadCmpZeroBeqOrBne
	BNE	L00066
* optim: branchToNextLocation
* Useless label L00068 removed
* Line core/hof.c:69: return with value
	LDD	6,U		variable `pos', declared at core/hof.c:59
* optim: branchToNextLocation
* Useless label L00010 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION put_num(): defined at core/hof.c:59
funcend_put_num	EQU *
funcsize_put_num	EQU	funcend_put_num-_put_num
_hof_format	EXPORT


*******************************************************************************

* FUNCTION hof_format(): defined at core/hof.c:72
_hof_format	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-5,S
* Formal parameter(s):
*      4,U:    2 bytes: in: const struct AnonStruct_core/hof.h:45 *: line 72
*      6,U:    2 bytes: buf: unsigned char *: line 72
*      8,U:    2 bytes: max: unsigned int: line 72
* Local non-static variable(s):
*     -5,U:    1 byte : c: char: line 83
*     -4,U:    2 bytes: pos: unsigned int: line 73
*     -2,U:    1 byte : i: unsigned char: line 74
*     -1,U:    1 byte : j: unsigned char: line 74
* Line core/hof.c:73: init of variable pos
	CLRA
	CLRB
	STD	-4,U		variable pos
* Line core/hof.c:76: for init
* Line core/hof.c:76: assignment: =
* optim: removeClr
	STB	-2,U		variable i
	LBRA	L00070		jump to for condition
L00069	EQU	*
* Line core/hof.c:76: for body
* Line core/hof.c:77: if
* optim: optimize16BitStackOps1
* optim: optimize16BitStackOps1
* optim: stripOpToDeadReg
* optim: stripOpToDeadReg
* PSHS B,A optim: optimizeStackOperations1
	LDD	-4,U		variable pos
* optim: combineConsecutiveOps
	ADDD	#$25		optim: combineConsecutiveOps
	CMPD	8,U		optim: optimize16BitStackOps1
	BLS	L00074		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00073 removed
* Line core/hof.c:77
* Line core/hof.c:77: return with value
	CLRA
	CLRB
* Emitted no code to cast `int' to `unsigned int'
	LBRA	L00011		return (core/hof.c:77)
L00074	EQU	*		else clause of if() started at core/hof.c:77
* Useless label L00075 removed
* Line core/hof.c:83: init of variable c
	LDB	#$01		1
	STB	-5,U		variable c
* Line core/hof.c:84: for init
* Line core/hof.c:84: assignment: =
	CLRB
	STB	-1,U		variable j
	BRA	L00077		jump to for condition
L00076	EQU	*
* Line core/hof.c:84: for body
* Line core/hof.c:85: if
	LDB	-5,U		variable `c', declared at core/hof.c:83
* optim: loadCmpZeroBeqOrBne
	BEQ	L00081		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00080 removed
* Line core/hof.c:85
* Line core/hof.c:85: assignment: =
	LDB	-1,U		variable j
	CLRA			extend byte index expression
	PSHS	B,A		preserve array index
	LDB	-2,U		variable i
* optim: stripExtraClrA_B
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	4,U		pointer in
	LEAX	D,X		add offset
	LEAX	,X		member name of AnonStruct_core/hof.h:45
	TFR	X,D
	ADDD	,S++		add stacked array index to array address in D
	TFR	D,X		put resulting address in X
	LDB	,X		get r-value
	STB	-5,U
L00081	EQU	*		else clause of if() started at core/hof.c:85
* Useless label L00082 removed
* Line core/hof.c:86: assignment: =
* Line core/hof.c:86: conditional expression
	LDB	-5,U		variable `c', declared at core/hof.c:83
* optim: loadCmpZeroBeqOrBne
	BEQ	L00084		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00083 removed
	LDB	-5,U		variable `c', declared at core/hof.c:83
	BRA	L00085		end of true expression of conditional
L00084	EQU	*
	LDB	#$2E		decimal 46 signed
L00085	EQU	*
* Cast from `char' to byte: result already in B
	PSHS	B
	LDB	-1,U		variable `j', declared at core/hof.c:74
	CLRA			promotion of binary operand
	ADDD	-4,U		optim: pushDLoadAdd
* 
* 
	LDX	6,U		pointer buf
	LEAX	D,X		add offset
	LDB	,S+
	STB	,X
* Useless label L00078 removed
* Line core/hof.c:84: for increment(s)
	INC	-1,U
L00077	EQU	*
* Line core/hof.c:84: for condition
	LDB	-1,U		variable j
	CMPB	#$19
	BLO	L00076
* optim: branchToNextLocation
* Useless label L00079 removed
* Line core/hof.c:89: assignment: =
	LDD	-4,U		variable pos
	ADDD	#$19		25
	STD	-4,U
* Line core/hof.c:90: assignment: =
	LDB	#$0D		decimal 13 signed
	PSHS	B
	LDD	-4,U		variable `pos', declared at core/hof.c:90
	ADDD	#1
	STD	-4,U
	SUBD	#1		post increment yields initial value
	LDX	6,U		pointer buf
	LEAX	D,X		add offset
	LDB	,S+
	STB	,X
* Line core/hof.c:90: assignment: =
	LDB	#$0A		decimal 10 signed
	PSHS	B
	LDD	-4,U		variable `pos', declared at core/hof.c:90
	ADDD	#1
	STD	-4,U
	SUBD	#1		post increment yields initial value
	LDX	6,U		pointer buf
	LEAX	D,X		add offset
	LDB	,S+
	STB	,X
* Line core/hof.c:91: assignment: =
* Line core/hof.c:91: function call: put_num()
	LDB	-2,U		variable i
* optim: stripOpToDeadReg
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	4,U		pointer in
	LEAX	D,X		add offset
	LDD	26,X		member score of AnonStruct_core/hof.h:45
	PSHS	B,A		argument 3 of put_num(): const int
	LDD	-4,U		variable `pos', declared at core/hof.c:73
	PSHS	B,A		argument 2 of put_num(): unsigned int
	LDD	6,U		variable `buf', declared at core/hof.c:72
	PSHS	B,A		argument 1 of put_num(): unsigned char *
	LBSR	_put_num
	LEAS	6,S
	STD	-4,U
* Line core/hof.c:92: assignment: =
* LDB #$0D optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
* optim: storeLoad
	ADDD	#1
	STD	-4,U
	SUBD	#1		post increment yields initial value
	LDX	6,U		pointer buf
	LEAX	D,X		add offset
	LDB	#13		optim: optimizeStackOperations1
	STB	,X
* Line core/hof.c:92: assignment: =
* LDB #$0A optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDD	-4,U		variable `pos', declared at core/hof.c:92
	ADDD	#1
	STD	-4,U
	SUBD	#1		post increment yields initial value
	LDX	6,U		pointer buf
	LEAX	D,X		add offset
	LDB	#10		optim: optimizeStackOperations1
	STB	,X
* Useless label L00071 removed
* Line core/hof.c:76: for increment(s)
	INC	-2,U
L00070	EQU	*
* Line core/hof.c:76: for condition
	LDB	-2,U		variable i
	CMPB	#$0A
	LBLO	L00069
* optim: branchToNextLocation
* Useless label L00072 removed
* Line core/hof.c:94: return with value
	LDD	-4,U		variable `pos', declared at core/hof.c:73
* optim: branchToNextLocation
L00011	EQU	*		end of hof_format()
	LEAS	,U
	PULS	U,PC
* END FUNCTION hof_format(): defined at core/hof.c:72
funcend_hof_format	EQU *
funcsize_hof_format	EQU	funcend_hof_format-_hof_format
_hof_offer	EXPORT


*******************************************************************************

* FUNCTION hof_offer(): defined at core/hof.c:97
_hof_offer	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-5,S
* Formal parameter(s):
*      4,U:    2 bytes: tbl: struct AnonStruct_core/hof.h:45 *: line 97
*      7,U:    1 byte : level: unsigned char: line 97
*      8,U:    2 bytes: name: const char *: line 97
*     10,U:    2 bytes: score: int: line 97
* Local non-static variable(s):
*     -5,U:    1 byte : c: char: line 120
*     -4,U:    1 byte : first: unsigned char: line 98
*     -3,U:    1 byte : second: unsigned char: line 99
*     -2,U:    1 byte : place: unsigned char: line 100
*     -1,U:    1 byte : j: unsigned char: line 100
* Line core/hof.c:98: init of variable first
* Line core/hof.c:98: function call: hof_index()
	CLRA
	CLRB
	PSHS	B,A		argument 2 of hof_index(): int
	LDB	7,U		variable `level', declared at core/hof.c:97
* optim: stripExtraClrA_B
	PSHS	B,A		argument 1 of hof_index(): unsigned char
	LBSR	_hof_index
	LEAS	4,S
	STB	-4,U		variable first
* Line core/hof.c:99: init of variable second
* Line core/hof.c:99: function call: hof_index()
	CLRA
	LDB	#$01		decimal 1 signed
	PSHS	B,A		argument 2 of hof_index(): int
	LDB	7,U		variable `level', declared at core/hof.c:97
* optim: stripExtraClrA_B
	PSHS	B,A		argument 1 of hof_index(): unsigned char
	LBSR	_hof_index
	LEAS	4,S
	STB	-3,U		variable second
* Line core/hof.c:102: if
	LDB	-4,U		variable first
* optim: stripOpToDeadReg
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	4,U		pointer tbl
	LEAX	D,X		add offset
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	10,U		variable `score', declared at core/hof.c:97
	CMPD	26,X		optim: optimizeStackOperations4
	BLE	L00087		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00086 removed
* Line core/hof.c:102
* Line core/hof.c:102: assignment: =
	LDB	-4,U		variable `first', declared at core/hof.c:98
	STB	-2,U
	BRA	L00088		jump over else clause
L00087	EQU	*		else clause of if() started at core/hof.c:102
* Line core/hof.c:104
* Line core/hof.c:103: if
	LDB	-3,U		variable second
* optim: stripOpToDeadReg
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	4,U		pointer tbl
	LEAX	D,X		add offset
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	10,U		variable `score', declared at core/hof.c:97
	CMPD	26,X		optim: optimizeStackOperations4
	BLE	L00090		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00089 removed
* Line core/hof.c:103
* Line core/hof.c:103: assignment: =
	LDB	-3,U		variable `second', declared at core/hof.c:99
	STB	-2,U
	BRA	L00091		jump over else clause
L00090	EQU	*		else clause of if() started at core/hof.c:103
* Line core/hof.c:104
	CLRB
	LBRA	L00012		return (core/hof.c:104)
L00091	EQU	*		end of if() started at core/hof.c:103
L00088	EQU	*		end of if() started at core/hof.c:102
* Line core/hof.c:108: if
	LDB	-2,U		variable place
	CMPB	-4,U		variable first
	BNE	L00093		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00092 removed
* Line core/hof.c:108
* Line core/hof.c:108: assignment: =
	LDB	-4,U		variable first
* optim: stripOpToDeadReg
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	4,U		pointer tbl
	LEAX	D,X		add offset
	PSHS	X		source struct address, for copyMem call
	LDB	-3,U		variable second
* optim: stripOpToDeadReg
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	4,U		pointer tbl
	LEAX	D,X		add offset
	LDD	#28		size of struct AnonStruct_core/hof.h:45
	LBSR	copyMem		preserves X
	LEAS	2,S		dispose of source struct address
L00093	EQU	*		else clause of if() started at core/hof.c:108
* Useless label L00094 removed
* Line core/hof.c:120: init of variable c
	LDB	#$01		1
	STB	-5,U		variable c
* Line core/hof.c:121: for init
* Line core/hof.c:121: assignment: =
	CLRB
	STB	-1,U		variable j
	BRA	L00096		jump to for condition
L00095	EQU	*
* Line core/hof.c:121: for body
* Line core/hof.c:122: if
	LDB	-5,U		variable `c', declared at core/hof.c:120
* optim: loadCmpZeroBeqOrBne
	BEQ	L00100		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00099 removed
* Line core/hof.c:122
* Line core/hof.c:122: assignment: =
	LDB	-1,U		variable j
	LDX	8,U		pointer name
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	STB	-5,U
L00100	EQU	*		else clause of if() started at core/hof.c:122
* Useless label L00101 removed
* Line core/hof.c:123: assignment: =
* Line core/hof.c:123: conditional expression
	LDB	-5,U		variable `c', declared at core/hof.c:120
* optim: loadCmpZeroBeqOrBne
	BEQ	L00103		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00102 removed
	LDB	-5,U		variable `c', declared at core/hof.c:120
	BRA	L00104		end of true expression of conditional
L00103	EQU	*
	LDB	#$2E		decimal 46 signed
L00104	EQU	*
	PSHS	B
	LDB	-1,U		variable j
	CLRA			extend byte index expression
	PSHS	B,A		preserve array index
	LDB	-2,U		variable place
* optim: stripExtraClrA_B
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	4,U		pointer tbl
	LEAX	D,X		add offset
	LEAX	,X		member name of AnonStruct_core/hof.h:45
	TFR	X,D
	ADDD	,S++		add stacked array index to array address in D
	TFR	D,X		put resulting address in X
	LDB	,S+
	STB	,X
* Useless label L00097 removed
* Line core/hof.c:121: for increment(s)
	INC	-1,U
L00096	EQU	*
* Line core/hof.c:121: for condition
	LDB	-1,U		variable j
	CMPB	#$19
	BLO	L00095
* optim: branchToNextLocation
* Useless label L00098 removed
* Line core/hof.c:126: assignment: =
* CLRB  optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-2,U		variable place
* optim: stripOpToDeadReg
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	4,U		pointer tbl
	LEAX	D,X		add offset
	LEAX	,X		member name of AnonStruct_core/hof.h:45
	TFR	X,D
* optim: stripConsecOppositeTFRs
* optim: optimizeLeax
	LDB	#0		optim: optimizeStackOperations1
	STB	25,X		optim: optimizeLeax
* Line core/hof.c:127: assignment: =
	LDD	10,U		variable `score', declared at core/hof.c:97
	PSHS	B,A
	LDB	-2,U		variable place
* optim: stripOpToDeadReg
	LDA	#28		size of array element
	MUL			get offset in bytes in D
	LDX	4,U		pointer tbl
	LEAX	D,X		add offset
* optim: optimizeLeax
	PULS	A,B		retrieve value to store
	STD	26,X		optim: optimizeLeax
	LDB	#1
* optim: branchToNextLocation
L00012	EQU	*		end of hof_offer()
	LEAS	,U
	PULS	U,PC
* END FUNCTION hof_offer(): defined at core/hof.c:97
funcend_hof_offer	EQU *
funcsize_hof_offer	EQU	funcend_hof_offer-_hof_offer


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Statically-initialized global variables
* Statically-initialized local static variables


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 3 utility routine(s).
DIV16	IMPORT
MUL16BY10	IMPORT
copyMem	IMPORT


*******************************************************************************

	END
