* 6809 assembly program generated by cmoc 0.1.86


	SECTION	code


_enemy_hp	IMPORT
_gal_commander	IMPORT
_tractored	IMPORT
_nova_quad	IMPORT
_nova_kills	IMPORT
_gal_enemies	IMPORT
_gal_base	IMPORT
_gal_stars	IMPORT
_gal_known	IMPORT
_gal_nova	IMPORT
_gal_star_gone	IMPORT
_sector	IMPORT
_ship	IMPORT
_hole_threw	IMPORT
_pod_alive	IMPORT
_plasma_shield	IMPORT
_bolt_cell	IMPORT
_bolt_quad	IMPORT
_hail_quad	IMPORT
_warp_hurt	IMPORT
_laser_overheated	IMPORT
_base_under_attack	IMPORT
_bases_lost	IMPORT
_trek_block_y	IMPORT
_trek_block_x	IMPORT
_planet_name	IMPORT
_planet_class_letter	IMPORT
_planets	IMPORT
_planet_count	IMPORT
_item_name	IMPORT
_inventory	IMPORT
_planet_evac_end	IMPORT
_planets	EXPORT
_planet_count	EXPORT
_inventory	EXPORT
_planet_evac_end	EXPORT
_planet_name	EXPORT
_planet_class_letter	EXPORT
_item_name	EXPORT
_trek_advance	IMPORT
_trek_advance_time	IMPORT
_trek_autonav_ok	IMPORT
_trek_bearing	IMPORT
_trek_combat_damage	IMPORT
_trek_dist	IMPORT
_trek_divert	IMPORT
_trek_dock	IMPORT
_trek_docked_safe	IMPORT
_trek_enemy_full_hp	IMPORT
_trek_enemy_turn	IMPORT
_trek_enter_quadrant	IMPORT
_trek_events_due	IMPORT
_trek_fire_laser	IMPORT
_trek_fire_ray	IMPORT
_trek_fire_torpedo	IMPORT
_trek_free_sector	IMPORT
_trek_game_state	IMPORT
_trek_hail	IMPORT
_trek_impulse_ok	IMPORT
_trek_is_scheduled	IMPORT
_trek_laser_begin_volley	IMPORT
_trek_laser_damage	IMPORT
_trek_laser_eff	IMPORT
_trek_life_replenish	IMPORT
_trek_lrscan_level	IMPORT
_trek_max_warp	IMPORT
_trek_move_delta	IMPORT
_trek_move_impulse	IMPORT
_trek_move_warp	IMPORT
_trek_new_game	IMPORT
_trek_plasma_bolt	IMPORT
_trek_rand	IMPORT
_trek_rand_n	IMPORT
_trek_rand_n16	IMPORT
_trek_rng_restore	IMPORT
_trek_rng_state	IMPORT
_trek_run_events	IMPORT
_trek_sched_deviate	IMPORT
_trek_sched_restore	IMPORT
_trek_schedule	IMPORT
_trek_scheduled	IMPORT
_trek_score	IMPORT
_trek_score_sheet	IMPORT
_trek_self_destruct	IMPORT
_trek_set_warp	IMPORT
_trek_shields_down	IMPORT
_trek_shields_up	IMPORT
_trek_shuttle_ok	IMPORT
_trek_srand	IMPORT
_trek_srscan_level	IMPORT
_trek_star_gone	IMPORT
_trek_take_hit	IMPORT
_trek_transporter_ok	IMPORT
_trek_tubes_available	IMPORT
_trek_turn_end	IMPORT
_trek_undock	IMPORT
_trek_unschedule	IMPORT
_trek_wreck_system	IMPORT
_planet_new	EXPORT


*******************************************************************************

* FUNCTION planet_new(): defined at core/planet.c:26
_planet_new	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-6,S
* Local non-static variable(s):
*     -6,U:    1 byte : q: unsigned char: line 41
*     -5,U:    1 byte : dup: unsigned char: line 41
*     -4,U:    1 byte : j: unsigned char: line 41
*     -3,U:    1 byte : cls1: unsigned char: line 41
*     -2,U:    1 byte : i: unsigned char: line 27
*     -1,U:    1 byte : settled: unsigned char: line 28
* Line core/planet.c:28: init of variable settled
	LDB	#$13		19
	STB	-1,U		variable settled
* Line core/planet.c:30: for init
* Line core/planet.c:30: assignment: =
	CLRB
	STB	-2,U		variable i
	BRA	L00099		jump to for condition
L00098	EQU	*
* Line core/planet.c:30: for body
* Line core/planet.c:30: assignment: =
	CLRA
* CLRB  optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-2,U		variable i
	LEAX	_inventory+0,PCR	address of array inventory
	ABX			add unsigned 8-bit offset
	LDB	#0		optim: optimizeStackOperations1
	STB	,X
* Useless label L00100 removed
* Line core/planet.c:30: for increment(s)
	INC	-2,U
L00099	EQU	*
* Line core/planet.c:30: for condition
	LDB	-2,U		variable i
	CMPB	#$05
	BLO	L00098
* optim: branchToNextLocation
* Useless label L00101 removed
* Line core/planet.c:31: assignment: =
	CLRA
	LDB	#$FF		decimal 255 signed
* optim: stripExtraPushPullB
* optim: optimizeLeax
* optim: stripExtraPushPullB
	STB	_ship+53,PCR	optim: optimizeLeax
* Line core/planet.c:32: assignment: =
* optim: stripExtraClrA_B
	CLRB
* optim: stripUselessPushPull
	LEAX	_ship+54,PCR	member rescues of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/planet.c:36: assignment: =
	LDD	#$FFFF		decimal 65535 unsigned
	STD	_planet_evac_end+0,PCR
* Line core/planet.c:38: assignment: =
* Line core/planet.c:38: function call: trek_rand_n()
	CLRA
	LDB	#$0A		decimal 10 signed
	PSHS	B,A		argument 1 of trek_rand_n(): int
	LBSR	_trek_rand_n
	LEAS	2,S
	PSHS	B
	CLRA
	LDB	#$0A		decimal 10 signed
	ADDB	,S+
	STB	_planet_count+0,PCR
* Line core/planet.c:40: for init
* Line core/planet.c:40: assignment: =
	CLRB
	STB	-2,U		variable i
	LBRA	L00103		jump to for condition
L00102	EQU	*
* Line core/planet.c:40: for body
* Line core/planet.c:47: for init
* Line core/planet.c:47: assignment: =
	LDB	#$01
	STB	-5,U		variable dup
	BRA	L00107		jump to for condition
L00106	EQU	*
* Line core/planet.c:47: for body
* Line core/planet.c:48: assignment: =
* Line core/planet.c:48: function call: trek_rand_n()
	CLRA
	LDB	#$40		constant expression: 64 decimal, signed
	PSHS	B,A		argument 1 of trek_rand_n(): int
	LBSR	_trek_rand_n
	LEAS	2,S
	STB	-6,U
* Line core/planet.c:49: assignment: =
	CLR	-5,U		variable dup
* Line core/planet.c:50: for init
* Line core/planet.c:50: assignment: =
	CLRB
	STB	-4,U		variable j
	BRA	L00111		jump to for condition
L00110	EQU	*
* Line core/planet.c:52: for body
* Line core/planet.c:51: if
* optim: optimize8BitStackOps
* optim: optimize8BitStackOps
	LDB	-4,U		variable j
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
* optimizeLoadDX
	LDB	D,X		member quad of AnonStruct_core/planet.h:231
	CMPB	-6,U		optim: optimize8BitStackOps
	BNE	L00115		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00114 removed
* Line core/planet.c:51
* Line core/planet.c:51: assignment: =
	LDB	#$01
	STB	-5,U		variable dup
	BRA	L00113		break
L00115	EQU	*		else clause of if() started at core/planet.c:51
* Useless label L00116 removed
* Useless label L00112 removed
* Line core/planet.c:50: for increment(s)
	INC	-4,U
L00111	EQU	*
* Line core/planet.c:50: for condition
	LDB	-4,U		variable j
	CMPB	-2,U		variable i
	BLO	L00110
* optim: branchToNextLocation
L00113	EQU	*		end for
* Useless label L00108 removed
L00107	EQU	*
* Line core/planet.c:47: for condition
	LDB	-5,U		variable `dup', declared at core/planet.c:41
* optim: loadCmpZeroBeqOrBne
	BNE	L00106
* optim: branchToNextLocation
* Useless label L00109 removed
* Line core/planet.c:53: assignment: =
	LDB	-6,U		variable `q', declared at core/planet.c:41
	PSHS	B
	LDB	-2,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LDB	,S+
	STB	,X
* Line core/planet.c:54: assignment: =
	CLRA
	CLRB
	PSHS	B
	LDB	-2,U		variable i
* optim: stripExtraClrA_B
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LEAX	1,X		member sec of AnonStruct_core/planet.h:231
	LDB	,S+
	STB	,X
* Line core/planet.c:55: assignment: =
* Line core/planet.c:55: function call: trek_rand_n()
	CLRA
	LDB	#$03		decimal 3 signed
	PSHS	B,A		argument 1 of trek_rand_n(): int
	LBSR	_trek_rand_n
	LEAS	2,S
	PSHS	B
	LDB	-2,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
* optim: optimizeLeax
	LDB	,S+
	STB	2,X		optim: optimizeLeax
* Line core/planet.c:56: assignment: =
	CLRA
	CLRB
	PSHS	B
	LDB	-2,U		variable i
* optim: stripExtraClrA_B
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
* optim: optimizeLeax
	LDB	,S+
	STB	4,X		optim: optimizeLeax
* Line core/planet.c:60: assignment: =
	CLRA
	LDB	#$01		decimal 1 signed
	PSHS	B
	LDB	-2,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LDB	2,X		member cls of AnonStruct_core/planet.h:231
	ADDB	,S+
	STB	-3,U
* Line core/planet.c:61: if
* Line core/planet.c:61: function call: trek_rand_n()
	CLRA
	LDB	#$05		decimal 5 signed
	PSHS	B,A		argument 1 of trek_rand_n(): int
	LBSR	_trek_rand_n
	LEAS	2,S
	PSHS	B
	LDB	-3,U		variable `cls1', declared at core/planet.c:41
	CMPB	,S+		compare with LSB
	BHI	L00118		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00117 removed
* Line core/planet.c:61
* Line core/planet.c:62: assignment: =
	CLRA
* LDB #$02 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-2,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
* optim: optimizeLeax
	LDB	#2		optim: optimizeStackOperations1
	STB	3,X		optim: optimizeLeax
* Line core/planet.c:66: assignment: =
	LDB	-2,U		variable `i', declared at core/planet.c:27
	STB	-1,U
	BRA	L00119		jump over else clause
L00118	EQU	*		else clause of if() started at core/planet.c:61
* Line core/planet.c:70
* Line core/planet.c:67: if
* Line core/planet.c:67: function call: trek_rand_n()
	CLRA
	LDB	#$02		decimal 2 signed
	PSHS	B,A		argument 1 of trek_rand_n(): int
	LBSR	_trek_rand_n
	LEAS	2,S
	TSTB
	BNE	L00121		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00120 removed
* Line core/planet.c:68
* Line core/planet.c:68: assignment: =
	CLRA
* LDB #$01 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-2,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
* optim: optimizeLeax
	LDB	#1		optim: optimizeStackOperations1
	STB	3,X		optim: optimizeLeax
	BRA	L00122		jump over else clause
L00121	EQU	*		else clause of if() started at core/planet.c:67
* Line core/planet.c:70
* Line core/planet.c:70: assignment: =
	CLRA
* LDB #$03 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-2,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
* optim: optimizeLeax
	LDB	#3		optim: optimizeStackOperations1
	STB	3,X		optim: optimizeLeax
L00122	EQU	*		end of if() started at core/planet.c:67
L00119	EQU	*		end of if() started at core/planet.c:61
* Useless label L00104 removed
* Line core/planet.c:40: for increment(s)
	INC	-2,U
L00103	EQU	*
* Line core/planet.c:40: for condition
	LDB	-2,U		variable i
	CMPB	_planet_count+0,PCR	variable planet_count
	LBLO	L00102
* optim: branchToNextLocation
* Useless label L00105 removed
* Line core/planet.c:72: if
	LDB	-1,U		variable settled
	CMPB	_planet_count+0,PCR	variable planet_count
	LBHS	L00127		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00123 removed
* Line core/planet.c:72
* Line core/planet.c:72: assignment: |=
	CLRA
* LDB #$08 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-1,U		variable settled
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LEAX	4,X		member flags of AnonStruct_core/planet.h:231
	LDB	,X
	ORB	#8		optim: optimizeStackOperations1
	STB	,X
* Useless label L00124 removed
* Useless label L00125 removed
	LBRA	L00127		jump to for condition
L00126	EQU	*
* Line core/planet.c:73: for body
* Line core/planet.c:77: assignment: =
	CLRA
* CLRB  optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-2,U		variable i
* optim: stripExtraClrA_B
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LDB	#0		optim: optimizeStackOperations1
	STB	,X
* Line core/planet.c:78: assignment: =
	CLRA
* CLRB  optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-2,U		variable i
* optim: stripExtraClrA_B
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
* optim: optimizeLeax
	LDB	#0		optim: optimizeStackOperations1
	STB	1,X		optim: optimizeLeax
* Line core/planet.c:79: assignment: =
	CLRA
* CLRB  optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-2,U		variable i
* optim: stripExtraClrA_B
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
* optim: optimizeLeax
	LDB	#0		optim: optimizeStackOperations1
	STB	2,X		optim: optimizeLeax
* Line core/planet.c:80: assignment: =
* LDD #$03 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-2,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
* optim: optimizeLeax
	LDB	#3		optim: optimizeStackOperations1
	STB	3,X		optim: optimizeLeax
* Line core/planet.c:81: assignment: =
	CLRA
* CLRB  optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-2,U		variable i
* optim: stripExtraClrA_B
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
* optim: optimizeLeax
	LDB	#0		optim: optimizeStackOperations1
	STB	4,X		optim: optimizeLeax
* Useless label L00128 removed
* Line core/planet.c:73: for increment(s)
	INC	-2,U
L00127	EQU	*
* Line core/planet.c:73: for condition
	LDB	-2,U		variable i
	CMPB	#$13
	LBLO	L00126
* optim: branchToNextLocation
* Useless label L00129 removed
* Useless label L00072 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION planet_new(): defined at core/planet.c:26
funcend_planet_new	EQU *
funcsize_planet_new	EQU	funcend_planet_new-_planet_new
_planet_place	EXPORT


*******************************************************************************

* FUNCTION planet_place(): defined at core/planet.c:89
_planet_place	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-3,S
* Local non-static variable(s):
*     -3,U:    1 byte : q: unsigned char: line 90
*     -2,U:    1 byte : i: unsigned char: line 91
*     -1,U:    1 byte : cell: unsigned char: line 91
* Line core/planet.c:90: init of variable q
	LDB	_ship+1,PCR	member quad_x of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B
	LDB	_ship+0,PCR	member quad_y of AnonStruct_core/trek.h:694, via variable ship
	LSLB
	LSLB
	LSLB
	ORB	,S+
	STB	-3,U		variable q
* Line core/planet.c:93: for init
* Line core/planet.c:93: assignment: =
	CLRB
	STB	-2,U		variable i
	BRA	L00131		jump to for condition
L00130	EQU	*
* Line core/planet.c:93: for body
* Line core/planet.c:94: if
* optim: optimize8BitStackOps
* optim: optimize8BitStackOps
	LDB	-2,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
* optimizeLoadDX
	LDB	D,X		member quad of AnonStruct_core/planet.h:231
	CMPB	-3,U		optim: optimize8BitStackOps
	BNE	L00132		 (optim: condBranchOverUncondBranch) (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00134 removed
* Line core/planet.c:94
* optim: condBranchOverUncondBranch
* Useless label L00135 removed
* Useless label L00136 removed
* Line core/planet.c:95: assignment: =
* Line core/planet.c:95: function call: trek_free_sector()
	LBSR	_trek_free_sector
	STB	-1,U
* Line core/planet.c:96: if
* optim: storeLoad
	CMPB	#$FF
	BEQ	L00132		 (optim: condBranchOverUncondBranch) (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00137 removed
* Line core/planet.c:96
* optim: condBranchOverUncondBranch
* Useless label L00138 removed
* Useless label L00139 removed
* Line core/planet.c:97: assignment: =
	CLRA
* LDB #$04 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-1,U		variable cell
	LEAX	_sector+0,PCR	address of array sector
	ABX			add unsigned 8-bit offset
	LDB	#4		optim: optimizeStackOperations1
	STB	,X
* Line core/planet.c:98: assignment: =
	LDB	-1,U		variable `cell', declared at core/planet.c:91
	PSHS	B
	LDB	-2,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
* optim: optimizeLeax
	LDB	,S+
	STB	1,X		optim: optimizeLeax
L00132	EQU	*
* Line core/planet.c:93: for increment(s)
	INC	-2,U
L00131	EQU	*
* Line core/planet.c:93: for condition
	LDB	-2,U		variable i
	CMPB	_planet_count+0,PCR	variable planet_count
	BLO	L00130
* optim: branchToNextLocation
* Useless label L00133 removed
* Useless label L00073 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION planet_place(): defined at core/planet.c:89
funcend_planet_place	EQU *
funcsize_planet_place	EQU	funcend_planet_place-_planet_place
_planet_quadrant_lost	EXPORT


*******************************************************************************

* FUNCTION planet_quadrant_lost(): defined at core/planet.c:102
_planet_quadrant_lost	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-1,S
* Formal parameter(s):
*      5,U:    1 byte : q: unsigned char: line 102
* Local non-static variable(s):
*     -1,U:    1 byte : i: unsigned char: line 103
* Line core/planet.c:104: for init
* Line core/planet.c:104: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00141		jump to for condition
L00140	EQU	*
* Line core/planet.c:107: for body
* Line core/planet.c:105: if
* optim: optimize8BitStackOps
* optim: optimize8BitStackOps
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
* optimizeLoadDX
	LDB	D,X		member quad of AnonStruct_core/planet.h:231
	CMPB	5,U		optim: optimize8BitStackOps
	BNE	L00145		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00144 removed
* Line core/planet.c:106
* Line core/planet.c:106: assignment: =
* LDD #$FFF7 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LDB	4,X		member flags of AnonStruct_core/planet.h:231
	ANDB	#247		optim: optimizeStackOperations1
	PSHS	B
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
* optim: optimizeLeax
	LDB	,S+
	STB	4,X		optim: optimizeLeax
L00145	EQU	*		else clause of if() started at core/planet.c:105
* Useless label L00146 removed
* Useless label L00142 removed
* Line core/planet.c:104: for increment(s)
	INC	-1,U
L00141	EQU	*
* Line core/planet.c:104: for condition
	LDB	-1,U		variable i
	CMPB	_planet_count+0,PCR	variable planet_count
	BLO	L00140
* optim: branchToNextLocation
* Useless label L00143 removed
* Useless label L00074 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION planet_quadrant_lost(): defined at core/planet.c:102
funcend_planet_quadrant_lost	EQU *
funcsize_planet_quadrant_lost	EQU	funcend_planet_quadrant_lost-_planet_quadrant_lost
_planet_settlement_lost	EXPORT


*******************************************************************************

* FUNCTION planet_settlement_lost(): defined at core/planet.c:109
_planet_settlement_lost	EQU	*
* Calling convention: Default
* Line core/planet.c:110: return with value
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	_ship+16,PCR	member stardate of AnonStruct_core/trek.h:694, via variable ship
	CMPD	_planet_evac_end+0,PCR	optim: optimizeStackOperations4
	BHI	L00147		if true
	CLRB
	BRA	L00075		false
L00147	EQU	*
	LDB	#1
* Useless label L00148 removed
* optim: branchToNextLocation
L00075	EQU	*		end of planet_settlement_lost()
	RTS
* END FUNCTION planet_settlement_lost(): defined at core/planet.c:109
funcend_planet_settlement_lost	EQU *
funcsize_planet_settlement_lost	EQU	funcend_planet_settlement_lost-_planet_settlement_lost
_planet_distress_here	EXPORT


*******************************************************************************

* FUNCTION planet_distress_here(): defined at core/planet.c:113
_planet_distress_here	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-2,S
* Local non-static variable(s):
*     -2,U:    1 byte : q: unsigned char: line 114
*     -1,U:    1 byte : i: unsigned char: line 115
* Line core/planet.c:114: init of variable q
	LDB	_ship+1,PCR	member quad_x of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B
	LDB	_ship+0,PCR	member quad_y of AnonStruct_core/trek.h:694, via variable ship
	LSLB
	LSLB
	LSLB
	ORB	,S+
	STB	-2,U		variable q
* Line core/planet.c:116: if
* Line core/planet.c:116: function call: planet_settlement_lost()
	LBSR	_planet_settlement_lost
	TSTB
	BEQ	L00150		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00149 removed
* Line core/planet.c:116
	CLRB
	BRA	L00076		return (core/planet.c:116)
L00150	EQU	*		else clause of if() started at core/planet.c:116
* Useless label L00151 removed
* Line core/planet.c:117: for init
* Line core/planet.c:117: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00153		jump to for condition
L00152	EQU	*
* Line core/planet.c:119: for body
* Line core/planet.c:118: if
	CLRA
* LDB #$08 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LDB	4,X		member flags of AnonStruct_core/planet.h:231
	ANDB	#8		optim: optimizeStackOperations1
* optim: optimizeAndbTstb
	BEQ	L00157		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00158 removed
* optim: optimize8BitStackOps
* optim: optimize8BitStackOps
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
* optimizeLoadDX
	LDB	D,X		member quad of AnonStruct_core/planet.h:231
	CMPB	-2,U		optim: optimize8BitStackOps
	BNE	L00157		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00156 removed
* Line core/planet.c:118
	LDB	#1
	BRA	L00076		return (core/planet.c:118)
L00157	EQU	*		else clause of if() started at core/planet.c:118
* Useless label L00159 removed
* Useless label L00154 removed
* Line core/planet.c:117: for increment(s)
	INC	-1,U
L00153	EQU	*
* Line core/planet.c:117: for condition
	LDB	-1,U		variable i
	CMPB	_planet_count+0,PCR	variable planet_count
	BLO	L00152
* optim: branchToNextLocation
* Useless label L00155 removed
	CLRB
* optim: branchToNextLocation
L00076	EQU	*		end of planet_distress_here()
	LEAS	,U
	PULS	U,PC
* END FUNCTION planet_distress_here(): defined at core/planet.c:113
funcend_planet_distress_here	EQU *
funcsize_planet_distress_here	EQU	funcend_planet_distress_here-_planet_distress_here
_planet_here	EXPORT


*******************************************************************************

* FUNCTION planet_here(): defined at core/planet.c:122
_planet_here	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-2,S
* Local non-static variable(s):
*     -2,U:    1 byte : q: unsigned char: line 123
*     -1,U:    1 byte : i: unsigned char: line 124
* Line core/planet.c:123: init of variable q
	LDB	_ship+1,PCR	member quad_x of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B
	LDB	_ship+0,PCR	member quad_y of AnonStruct_core/trek.h:694, via variable ship
	LSLB
	LSLB
	LSLB
	ORB	,S+
	STB	-2,U		variable q
* Line core/planet.c:125: for init
* Line core/planet.c:125: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00161		jump to for condition
L00160	EQU	*
* Line core/planet.c:127: for body
* Line core/planet.c:126: if
* optim: optimize8BitStackOps
* optim: optimize8BitStackOps
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
* optimizeLoadDX
	LDB	D,X		member quad of AnonStruct_core/planet.h:231
	CMPB	-2,U		optim: optimize8BitStackOps
	BNE	L00165		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00164 removed
* Line core/planet.c:126
* Line core/planet.c:126: return with value
	LDB	-1,U		variable `i', declared at core/planet.c:124
	BRA	L00077		return (core/planet.c:126)
L00165	EQU	*		else clause of if() started at core/planet.c:126
* Useless label L00166 removed
* Useless label L00162 removed
* Line core/planet.c:125: for increment(s)
	INC	-1,U
L00161	EQU	*
* Line core/planet.c:125: for condition
	LDB	-1,U		variable i
	CMPB	_planet_count+0,PCR	variable planet_count
	BLO	L00160
* optim: branchToNextLocation
* Useless label L00163 removed
	LDB	#255
* optim: branchToNextLocation
L00077	EQU	*		end of planet_here()
	LEAS	,U
	PULS	U,PC
* END FUNCTION planet_here(): defined at core/planet.c:122
funcend_planet_here	EQU *
funcsize_planet_here	EQU	funcend_planet_here-_planet_here


*******************************************************************************

* FUNCTION adjacent(): defined at core/planet.c:132
_adjacent	EQU	*
.static.function.adjacent	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-4,S
* Formal parameter(s):
*      5,U:    1 byte : cell: unsigned char: line 132
* Local non-static variable(s):
*     -4,U:    1 byte : cy: unsigned char: line 133
*     -3,U:    1 byte : cx: unsigned char: line 133
*     -2,U:    1 byte : dy: unsigned char: line 134
*     -1,U:    1 byte : dx: unsigned char: line 135
* Line core/planet.c:133: init of variable cy
	LDB	5,U		variable `cell', declared at core/planet.c:132
	LSRB
	LSRB
	LSRB
	STB	-4,U		variable cy
* Line core/planet.c:133: init of variable cx
	LDB	5,U		variable cell
	ANDB	#$07
	STB	-3,U		variable cx
* Line core/planet.c:134: init of variable dy
* Line core/planet.c:134: conditional expression
* optim: removePushBFromLdbPushLdbCmp
* optim: removePushBFromLdbPushLdbCmp
	LDB	-4,U		variable `cy', declared at core/planet.c:133
	CMPB	_ship+2,PCR	compare with LSB
	BLS	L00168		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00167 removed
	LDB	_ship+2,PCR	member sec_y of AnonStruct_core/trek.h:694, via variable ship
* optim: removePushBBeforeSubB
	NEGB			optim: removePushBBeforeSubB
	ADDB	-4,U		optim: removePushBBeforeSubB
	BRA	L00169		end of true expression of conditional
L00168	EQU	*
	LDB	-4,U		variable `cy', declared at core/planet.c:133
* optim: removePushBBeforeSubB
	NEGB			optim: removePushBBeforeSubB
	ADDB	_ship+2,PCR	optim: removePushBBeforeSubB
L00169	EQU	*
	STB	-2,U		variable dy
* Line core/planet.c:135: init of variable dx
* Line core/planet.c:135: conditional expression
* optim: removePushBFromLdbPushLdbCmp
* optim: removePushBFromLdbPushLdbCmp
	LDB	-3,U		variable `cx', declared at core/planet.c:133
	CMPB	_ship+3,PCR	compare with LSB
	BLS	L00171		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00170 removed
	LDB	_ship+3,PCR	member sec_x of AnonStruct_core/trek.h:694, via variable ship
* optim: removePushBBeforeSubB
	NEGB			optim: removePushBBeforeSubB
	ADDB	-3,U		optim: removePushBBeforeSubB
	BRA	L00172		end of true expression of conditional
L00171	EQU	*
	LDB	-3,U		variable `cx', declared at core/planet.c:133
* optim: removePushBBeforeSubB
	NEGB			optim: removePushBBeforeSubB
	ADDB	_ship+3,PCR	optim: removePushBBeforeSubB
L00172	EQU	*
	STB	-1,U		variable dx
* Line core/planet.c:136: return with value
	LDB	-2,U		variable dy
	CMPB	#$01
	BLS	L00174		if true
	CLRB
	BRA	L00175		false
L00174	EQU	*
	LDB	#1
L00175	EQU	*
	TSTB			&&
	BEQ	L00078		&& at core/planet.c:136 yields false, B == 0
	LDB	-1,U		variable dx
	CMPB	#$01
	BLS	L00176		if true
	CLRB
	BRA	L00177		false
L00176	EQU	*
	LDB	#1
L00177	EQU	*
	TSTB			&&
	BEQ	L00078		&& at core/planet.c:136 yields false, B == 0
	LDB	#1		&& yields true
* Useless label L00173 removed
* optim: branchToNextLocation
L00078	EQU	*		end of adjacent()
	LEAS	,U
	PULS	U,PC
* END FUNCTION adjacent(): defined at core/planet.c:132
funcend_adjacent	EQU *
funcsize_adjacent	EQU	funcend_adjacent-_adjacent
_trek_orbit	EXPORT


*******************************************************************************

* FUNCTION trek_orbit(): defined at core/planet.c:139
_trek_orbit	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-2,S
* Local non-static variable(s):
*     -2,U:    1 byte : q: unsigned char: line 140
*     -1,U:    1 byte : i: unsigned char: line 141
* Line core/planet.c:140: init of variable q
	LDB	_ship+1,PCR	member quad_x of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B
	LDB	_ship+0,PCR	member quad_y of AnonStruct_core/trek.h:694, via variable ship
	LSLB
	LSLB
	LSLB
	ORB	,S+
	STB	-2,U		variable q
* Line core/planet.c:143: if
	CLRA
* optim: stripConsecutiveLoadsToSameReg
* PSHS B,A optim: optimizeStackOperations1
	LDB	_ship+53,PCR	member orbiting of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraClrA_B
	CMPD	#255		optim: optimizeStackOperations1
	BEQ	L00179		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00178 removed
* Line core/planet.c:143
	LDB	#2
	LBRA	L00079		return (core/planet.c:143)
L00179	EQU	*		else clause of if() started at core/planet.c:143
* Useless label L00180 removed
* Line core/planet.c:149: for init
* Line core/planet.c:149: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00182		jump to for condition
L00181	EQU	*
* Line core/planet.c:149: for body
* Line core/planet.c:150: if
* optim: optimize8BitStackOps
* optim: optimize8BitStackOps
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
* optimizeLoadDX
	LDB	D,X		member quad of AnonStruct_core/planet.h:231
	CMPB	-2,U		optim: optimize8BitStackOps
	BNE	L00183		 (optim: condBranchOverUncondBranch) (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00185 removed
* Line core/planet.c:150
* optim: condBranchOverUncondBranch
* Useless label L00186 removed
* Useless label L00187 removed
* Line core/planet.c:151: if
* Line core/planet.c:151: function call: adjacent()
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LDB	1,X		member sec of AnonStruct_core/planet.h:231
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of adjacent(): unsigned char
	LBSR	_adjacent
	LEAS	2,S
	TSTB
	BEQ	L00183		 (optim: condBranchOverUncondBranch)
* optim: branchToNextLocation
* Useless label L00188 removed
* Line core/planet.c:151
* optim: condBranchOverUncondBranch
* Useless label L00189 removed
* Useless label L00190 removed
* Line core/planet.c:152: assignment: =
* optim: optimize8BitStackOps
* optim: optimize8BitStackOps
* optim: optimizeLeax
	LDB	-1,U		optim: optimize8BitStackOps
	STB	_ship+53,PCR	optim: optimizeLeax
* Line core/planet.c:154: assignment: |=
	CLRA
* LDB #$01 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LEAX	4,X		member flags of AnonStruct_core/planet.h:231
	LDB	,X
	ORB	#1		optim: optimizeStackOperations1
	STB	,X
	CLRB
	BRA	L00079		return (core/planet.c:155)
L00183	EQU	*
* Line core/planet.c:149: for increment(s)
	INC	-1,U
L00182	EQU	*
* Line core/planet.c:149: for condition
	LDB	-1,U		variable i
	CMPB	_planet_count+0,PCR	variable planet_count
	LBLO	L00181
* optim: branchToNextLocation
* Useless label L00184 removed
	LDB	#1
* optim: branchToNextLocation
L00079	EQU	*		end of trek_orbit()
	LEAS	,U
	PULS	U,PC
* END FUNCTION trek_orbit(): defined at core/planet.c:139
funcend_trek_orbit	EQU *
funcsize_trek_orbit	EQU	funcend_trek_orbit-_trek_orbit
_trek_leave_orbit	EXPORT


*******************************************************************************

* FUNCTION trek_leave_orbit(): defined at core/planet.c:160
_trek_leave_orbit	EQU	*
* Calling convention: Default
* Line core/planet.c:161: assignment: =
	CLRA
* LDB #$FF optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
* optim: optimizeLeax
	LDB	#255		optim: optimizeStackOperations1
	STB	_ship+53,PCR	optim: optimizeLeax
* Useless label L00080 removed
	RTS
* END FUNCTION trek_leave_orbit(): defined at core/planet.c:160
funcend_trek_leave_orbit	EQU *
funcsize_trek_leave_orbit	EQU	funcend_trek_leave_orbit-_trek_leave_orbit
_trek_land	EXPORT


*******************************************************************************

* FUNCTION trek_land(): defined at core/planet.c:166
_trek_land	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-4,S
* Formal parameter(s):
*      5,U:    1 byte : how: unsigned char: line 166
*      6,U:    2 bytes: casualties: unsigned int *: line 166
* Local non-static variable(s):
*     -4,U:    2 bytes: p: struct AnonStruct_core/planet.h:231 *: line 167
*     -2,U:    2 bytes: lost: unsigned int: line 168
* Line core/planet.c:170: if
	LDD	6,U		variable `casualties', declared at core/planet.c:166
* optim: loadCmpZeroBeqOrBne
	BEQ	L00192		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00191 removed
* Line core/planet.c:170
* Line core/planet.c:170: assignment: =
	CLRA
	CLRB
* optim: stripUselessPushPull
* optim: optimizeLdx
* optim: stripUselessPushPull
	STD	[6,U]		optim: optimizeLdx
L00192	EQU	*		else clause of if() started at core/planet.c:170
* Useless label L00193 removed
* Line core/planet.c:171: if
	CLRA
* optim: stripConsecutiveLoadsToSameReg
* PSHS B,A optim: optimizeStackOperations1
	LDB	_ship+53,PCR	member orbiting of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraClrA_B
	CMPD	#255		optim: optimizeStackOperations1
	BNE	L00195		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00194 removed
* Line core/planet.c:171
	CLRB
	LBRA	L00081		return (core/planet.c:171)
L00195	EQU	*		else clause of if() started at core/planet.c:171
* Useless label L00196 removed
* Line core/planet.c:176: if
	LDB	_ship+15,PCR	member shields_up of AnonStruct_core/trek.h:694, via variable ship
* optim: loadCmpZeroBeqOrBne
	BEQ	L00198		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00197 removed
* Line core/planet.c:176
	LDB	#1
	LBRA	L00081		return (core/planet.c:176)
L00198	EQU	*		else clause of if() started at core/planet.c:176
* Useless label L00199 removed
* Line core/planet.c:178: if
	LDB	5,U		variable how
	CMPB	#$01
	BNE	L00201		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00200 removed
* Line core/planet.c:178
* Line core/planet.c:179: if
* Line core/planet.c:179: function call: trek_shuttle_ok()
	LBSR	_trek_shuttle_ok
	TSTB
	BNE	L00205
* optim: branchToNextLocation
* Useless label L00202 removed
* Line core/planet.c:179
	LDB	#2
	LBRA	L00081		return (core/planet.c:179)
* Useless label L00203 removed
* Useless label L00204 removed
* optim: instrFollowingUncondBranch
L00201	EQU	*		else clause of if() started at core/planet.c:178
* Line core/planet.c:180
* Line core/planet.c:181: if
* Line core/planet.c:181: function call: trek_transporter_ok()
	LBSR	_trek_transporter_ok
	TSTB
	BNE	L00207
* optim: branchToNextLocation
* Useless label L00206 removed
* Line core/planet.c:181
	LDB	#2
	LBRA	L00081		return (core/planet.c:181)
L00207	EQU	*		else clause of if() started at core/planet.c:181
* Useless label L00208 removed
L00205	EQU	*		end of if() started at core/planet.c:178
* Line core/planet.c:184: assignment: =
	LDB	_ship+53,PCR	member orbiting of AnonStruct_core/trek.h:694, via variable ship
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	TFR	X,D		address-of operator
	STD	-4,U
* Line core/planet.c:190: if
	CLRA
* LDB #$08 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDX	-4,U		variable p
	LDB	4,X		member flags of AnonStruct_core/planet.h:231
	ANDB	#8		optim: optimizeStackOperations1
* optim: optimizeAndbTstb
	BEQ	L00210		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00211 removed
* Line core/planet.c:190: function call: planet_settlement_lost()
	LBSR	_planet_settlement_lost
	TSTB
	BNE	L00210
* optim: branchToNextLocation
* Useless label L00209 removed
* Line core/planet.c:190
* Line core/planet.c:191: assignment: =
	CLRA
* LDB #$02 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
* LDD #$FFF7 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDX	-4,U		variable p
	LDB	4,X		member flags of AnonStruct_core/planet.h:231
	ANDB	#247		optim: optimizeStackOperations1
	ORB	#2		optim: optimizeStackOperations1
* optim: stripExtraPushPullB
	LDX	-4,U		variable p
* optim: optimizeLeax
* optim: stripExtraPushPullB
	STB	4,X		optim: optimizeLeax
* Line core/planet.c:192: post-increment
	LEAX	_ship+54,PCR	member rescues of AnonStruct_core/trek.h:694, via variable ship
	LDD	,X
	ADDD	#1
	STD	,X
	LDB	#5
	LBRA	L00081		return (core/planet.c:193)
L00210	EQU	*		else clause of if() started at core/planet.c:190
* Useless label L00212 removed
* Line core/planet.c:200: if
	LDB	5,U		variable how
	CMPB	#$01
	BNE	L00214		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00213 removed
* Line core/planet.c:200
* Line core/planet.c:200: function call: trek_advance_time()
	CLRA
	LDB	#$02		decimal 2 signed
	PSHS	B,A		argument 1 of trek_advance_time(): int
	LBSR	_trek_advance_time
	LEAS	2,S
L00214	EQU	*		else clause of if() started at core/planet.c:200
* Useless label L00215 removed
* Line core/planet.c:221: if
* Line core/planet.c:221: function call: trek_rand_n()
	CLRA
	LDB	#$05		decimal 5 signed
	PSHS	B,A		argument 1 of trek_rand_n(): int
	LBSR	_trek_rand_n
	LEAS	2,S
	TSTB
	BNE	L00217		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00216 removed
* Line core/planet.c:221
* Line core/planet.c:223: assignment: =
* Line core/planet.c:223: function call: trek_rand_n()
	CLRA
	LDB	#$05		decimal 5 signed
	PSHS	B,A		argument 1 of trek_rand_n(): int
	LBSR	_trek_rand_n
	LEAS	2,S
	PSHS	B
	CLRA
	LDB	#$02		decimal 2 signed
	ADDB	,S+
* optim: stripExtraClrA_B
	STD	-2,U
* Line core/planet.c:224: assignment: =
* optim: storeLoad
	ADDD	_ship+41,PCR	optim: pushDLoadAdd
* 
* 
* optim: stripUselessPushPull
* optim: optimizeLeax
* optim: stripUselessPushPull
	STD	_ship+41,PCR	optim: optimizeLeax
* Line core/planet.c:225: if
	LDD	6,U		variable `casualties', declared at core/planet.c:166
* optim: loadCmpZeroBeqOrBne
	BEQ	L00219		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00218 removed
* Line core/planet.c:225
* Line core/planet.c:225: assignment: =
	LDD	-2,U		variable `lost', declared at core/planet.c:168
* optim: stripUselessPushPull
* optim: optimizeLdx
* optim: stripUselessPushPull
	STD	[6,U]		optim: optimizeLdx
L00219	EQU	*		else clause of if() started at core/planet.c:225
* Useless label L00220 removed
* Line core/planet.c:226: assignment: |=
	CLRA
* LDB #$02 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDX	-4,U		variable p
	LEAX	4,X		member flags of AnonStruct_core/planet.h:231
	LDB	,X
	ORB	#2		optim: optimizeStackOperations1
	STB	,X
	LDB	#6
	LBRA	L00081		return (core/planet.c:227)
L00217	EQU	*		else clause of if() started at core/planet.c:221
* Useless label L00221 removed
* Line core/planet.c:236: if
	CLRA
* LDB #$02 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDX	-4,U		variable p
	LDB	4,X		member flags of AnonStruct_core/planet.h:231
	ANDB	#2		optim: optimizeStackOperations1
* optim: optimizeAndbTstb
	BEQ	L00223		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00222 removed
* Line core/planet.c:236
	LDB	#7
	BRA	L00081		return (core/planet.c:236)
L00223	EQU	*		else clause of if() started at core/planet.c:236
* Useless label L00224 removed
* Line core/planet.c:238: switch
	LDX	-4,U		variable p
	LDB	3,X		member find of AnonStruct_core/planet.h:231
* Switch at core/planet.c:238 uses if-else sequence: IF_ELSE=15, JUMP_TABLE=24
	CMPB	#$02		case 2
	BEQ	L00226
	CMPB	#$01		case 1
	BEQ	L00227
	BRA	L00228		switch default
L00226	EQU	*		case 2
* Line core/planet.c:240: assignment: |=
	CLRA
* LDB #$02 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDX	-4,U		variable p
	LEAX	4,X		member flags of AnonStruct_core/planet.h:231
	LDB	,X
	ORB	#2		optim: optimizeStackOperations1
	STB	,X
* Line core/planet.c:244: if
* optim: stripExtraClrA_B
* optim: stripConsecutiveLoadsToSameReg
* PSHS B,A optim: optimizeStackOperations1
	LDB	_inventory+4,PCR	index 4 in array inventory[]
* optim: stripExtraClrA_B
	CMPD	#255		optim: optimizeStackOperations1
	BHS	L00230		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00229 removed
* Line core/planet.c:244
* Line core/planet.c:244: post-increment
* optim: optimizeLeax
	INC	_inventory+4,PCR	optim: optimizeLeax
L00230	EQU	*		else clause of if() started at core/planet.c:244
* Useless label L00231 removed
	LDB	#4
	BRA	L00081		return (core/planet.c:245)
L00227	EQU	*		case 1
* Line core/planet.c:255: assignment: |=
	CLRA
* LDB #$02 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDX	-4,U		variable p
	LEAX	4,X		member flags of AnonStruct_core/planet.h:231
	LDB	,X
	ORB	#2		optim: optimizeStackOperations1
	STB	,X
	LDB	#8
	BRA	L00081		return (core/planet.c:256)
L00228	EQU	*		default
* Line core/planet.c:259: assignment: |=
	CLRA
* LDB #$02 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDX	-4,U		variable p
	LEAX	4,X		member flags of AnonStruct_core/planet.h:231
	LDB	,X
	ORB	#2		optim: optimizeStackOperations1
	STB	,X
	LDB	#3
	BRA	L00081		return (core/planet.c:260)
* Useless label L00225 removed
L00081	EQU	*		end of trek_land()
	LEAS	,U
	PULS	U,PC
* END FUNCTION trek_land(): defined at core/planet.c:166
funcend_trek_land	EQU *
funcsize_trek_land	EQU	funcend_trek_land-_trek_land
_trek_capture_supplies	EXPORT


*******************************************************************************

* FUNCTION trek_capture_supplies(): defined at core/planet.c:266
_trek_capture_supplies	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-2,S
* Local non-static variable(s):
*     -2,U:    1 byte : got: unsigned char: line 267
*     -1,U:    1 byte : i: unsigned char: line 267
* Line core/planet.c:267: init of variable got
	CLR	-2,U		variable got
* Line core/planet.c:269: if
* Line core/planet.c:269: function call: trek_rand_n()
	CLRA
	LDB	#$04		decimal 4 signed
	PSHS	B,A		argument 1 of trek_rand_n(): int
	LBSR	_trek_rand_n
	LEAS	2,S
	TSTB
	BNE	L00233		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00232 removed
* Line core/planet.c:269
	CLRB
	LBRA	L00082		return (core/planet.c:269)
L00233	EQU	*		else clause of if() started at core/planet.c:269
* Useless label L00234 removed
* Line core/planet.c:271: for init
* Line core/planet.c:271: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00236		jump to for condition
L00235	EQU	*
* Line core/planet.c:278: for body
* Line core/planet.c:272: if
	CLRA
	LDB	#$01		decimal 1 signed
	PSHS	B,A
* Line core/planet.c:272: function call: trek_rand_n()
	LDB	-1,U		variable i
	ADDB	#$03		3
* optim: stripExtraClrA_B
	PSHS	B,A		argument 1 of trek_rand_n(): unsigned char
	LBSR	_trek_rand_n
	LEAS	2,S
	CLRA			promotion of binary operand
	CMPD	,S++
	BHI	L00240		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00239 removed
* Line core/planet.c:272
* Line core/planet.c:273: if
	CLRA
* optim: stripConsecutiveLoadsToSameReg
* PSHS B,A optim: optimizeStackOperations1
	LDB	-1,U		variable i
	LEAX	_inventory+0,PCR	address of array inventory
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
* optim: stripExtraClrA_B
	CMPD	#255		optim: optimizeStackOperations1
	BHS	L00242		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00241 removed
* Line core/planet.c:273
* Line core/planet.c:273: post-increment
	LDB	-1,U		variable i
	LEAX	_inventory+0,PCR	address of array inventory
	ABX			add unsigned 8-bit offset
	INC	,X
L00242	EQU	*		else clause of if() started at core/planet.c:273
* Useless label L00243 removed
* Line core/planet.c:274: assignment: =
	CLRA
	LDB	#$01		decimal 1 unsigned
	PSHS	B,A		left side of shift: used and popped by shiftLeft
	LDB	-1,U		variable `i', declared at core/planet.c:267
* optim: stripExtraClrA_B
	LBSR	shiftLeft
	PSHS	B,A
	LDB	-2,U		variable `got', declared at core/planet.c:267
	CLRA			promotion of binary operand
	ORA	,S+
	ORB	,S+
* Cast from `unsigned int' to byte: result already in B
	STB	-2,U
L00240	EQU	*		else clause of if() started at core/planet.c:272
* Useless label L00244 removed
* Useless label L00237 removed
* Line core/planet.c:271: for increment(s)
	INC	-1,U
L00236	EQU	*
* Line core/planet.c:271: for condition
	LDB	-1,U		variable i
	CMPB	#$03
	LBLO	L00235
* optim: branchToNextLocation
* Useless label L00238 removed
* Line core/planet.c:278: if
	LDB	_inventory+3,PCR	index 3 in array inventory[]
	CMPB	#253
	BHI	L00246		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00245 removed
* Line core/planet.c:280
* Line core/planet.c:280: assignment: =
	CLRA
* LDB #$02 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	_inventory+3,PCR	index 3 in array inventory[]
	ADDB	#2		optim: optimizeStackOperations1
* optim: stripExtraPushPullB
* optim: optimizeLeax
* optim: stripExtraPushPullB
	STB	_inventory+3,PCR	optim: optimizeLeax
L00246	EQU	*		else clause of if() started at core/planet.c:278
* Useless label L00247 removed
* Line core/planet.c:281: assignment: =
	LDB	-2,U		variable got
	ORB	#$08
	STB	-2,U
* Line core/planet.c:283: return with value
* optim: storeLoad
* optim: branchToNextLocation
L00082	EQU	*		end of trek_capture_supplies()
	LEAS	,U
	PULS	U,PC
* END FUNCTION trek_capture_supplies(): defined at core/planet.c:266
funcend_trek_capture_supplies	EQU *
funcsize_trek_capture_supplies	EQU	funcend_trek_capture_supplies-_trek_capture_supplies
_trek_energium_allowed	EXPORT


*******************************************************************************

* FUNCTION trek_energium_allowed(): defined at core/planet.c:286
_trek_energium_allowed	EQU	*
* Calling convention: Default
* Line core/planet.c:289: if
* LDD #$03E8 optim: optimizeStackOperations1
* PSHS B,A optim: optimizeStackOperations1
	LDD	_ship+4,PCR	member energy of AnonStruct_core/trek.h:694, via variable ship
	CMPD	#1000		optim: optimizeStackOperations1
	BLO	L00249		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00248 removed
* Line core/planet.c:289
	CLRB
	BRA	L00083		return (core/planet.c:289)
L00249	EQU	*		else clause of if() started at core/planet.c:289
* Useless label L00250 removed
* Line core/planet.c:290: if
* LDD #$04E2 optim: optimizeStackOperations1
* PSHS B,A optim: optimizeStackOperations1
	LDD	_ship+8,PCR	member shields of AnonStruct_core/trek.h:694, via variable ship
	CMPD	#1250		optim: optimizeStackOperations1
	BLO	L00252		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00251 removed
* Line core/planet.c:290
	CLRB
	BRA	L00083		return (core/planet.c:290)
L00252	EQU	*		else clause of if() started at core/planet.c:290
* Useless label L00253 removed
	LDB	#1
* optim: branchToNextLocation
L00083	EQU	*		end of trek_energium_allowed()
	RTS
* END FUNCTION trek_energium_allowed(): defined at core/planet.c:286
funcend_trek_energium_allowed	EQU *
funcsize_trek_energium_allowed	EQU	funcend_trek_energium_allowed-_trek_energium_allowed
_trek_use_energium	EXPORT


*******************************************************************************

* FUNCTION trek_use_energium(): defined at core/planet.c:294
_trek_use_energium	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-7,S
* Formal parameter(s):
*      4,U:    2 bytes: ev: struct AnonStruct_core/trek.h:1255 *: line 294
*      7,U:    1 byte : max: unsigned char: line 294
* Local non-static variable(s):
*     -7,U:    1 byte : roll: unsigned char: line 295
*     -6,U:    2 bytes: v: unsigned int: line 296
*     -4,U:    2 bytes: gain: unsigned int: line 296
*     -2,U:    2 bytes: loss: unsigned int: line 296
* Line core/planet.c:300: if
	LDB	_inventory+4,PCR	index 4 in array inventory[]
* optim: loadCmpZeroBeqOrBne
	BNE	L00255
* optim: branchToNextLocation
* Useless label L00254 removed
* Line core/planet.c:300
	CLRB
	LBRA	L00084		return (core/planet.c:300)
L00255	EQU	*		else clause of if() started at core/planet.c:300
* Useless label L00256 removed
* Line core/planet.c:301: if
* Line core/planet.c:301: function call: trek_energium_allowed()
	LBSR	_trek_energium_allowed
	TSTB
	BNE	L00258
* optim: branchToNextLocation
* Useless label L00257 removed
* Line core/planet.c:301
	LDB	#1
	LBRA	L00084		return (core/planet.c:301)
L00258	EQU	*		else clause of if() started at core/planet.c:301
* Useless label L00259 removed
* Line core/planet.c:303: post-decrement
	LEAX	_inventory+4,PCR	index 4 in array inventory[]
	DEC	,X
* Line core/planet.c:307: assignment: =
* Line core/planet.c:307: function call: trek_rand_n()
	CLRA
	LDB	#$06		decimal 6 signed
	PSHS	B,A		argument 1 of trek_rand_n(): int
	LBSR	_trek_rand_n
	LEAS	2,S
	STB	-7,U
* Line core/planet.c:309: if
* optim: storeLoad
* optim: loadCmpZeroBeqOrBne
	BNE	L00261		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00260 removed
* Line core/planet.c:309
* Line core/planet.c:313: assignment: =
* Line core/planet.c:313: function call: trek_rand_n16()
	LDD	#$03E8		decimal 1000 signed
	PSHS	B,A		argument 1 of trek_rand_n16(): int
	LBSR	_trek_rand_n16
	LEAS	2,S
	STD	-2,U
* Line core/planet.c:314: assignment: =
* Line core/planet.c:314: conditional expression
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
* optim: storeLoad
	CMPD	_ship+4,PCR	optim: optimizeStackOperations4
	BLO	L00263		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00262 removed
	CLRA
	CLRB
	BRA	L00264		end of true expression of conditional
L00263	EQU	*
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	_ship+4,PCR	member energy of AnonStruct_core/trek.h:694, via variable ship
	SUBD	-2,U		optim: optimizeStackOperations4
L00264	EQU	*
* Emitted no code to cast `int' to `unsigned int'
* optim: stripUselessPushPull
* optim: optimizeLeax
* optim: stripUselessPushPull
	STD	_ship+4,PCR	optim: optimizeLeax
	LDB	#3
	LBRA	L00084		return (core/planet.c:315)
L00261	EQU	*		else clause of if() started at core/planet.c:309
* Useless label L00265 removed
* Line core/planet.c:317: if
	LDB	-7,U		variable roll
	CMPB	#$02
	BHI	L00267		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00266 removed
* Line core/planet.c:317
	LDB	#4
	LBRA	L00084		return (core/planet.c:317)
L00267	EQU	*		else clause of if() started at core/planet.c:317
* Useless label L00268 removed
* Line core/planet.c:323: assignment: =
	CLRA
	LDB	#$05		decimal 5 signed
	STD	-6,U
* Line core/planet.c:325: assignment: =
* optim: storeLoad
	PSHS	B,A
* Line core/planet.c:325: function call: trek_rand_n16()
	LDD	#$02BC		decimal 700 signed
	PSHS	B,A		argument 1 of trek_rand_n16(): int
	LBSR	_trek_rand_n16
	LEAS	2,S
	ADDD	#$02BC		optim: pushDLoadAdd
* 
* 
	PULS	X
	LBSR	MUL16
	STD	-4,U
* Line core/planet.c:326: assignment: =
* optim: storeLoad
	ADDD	_ship+4,PCR	optim: pushDLoadAdd
* 
* 
* optim: stripUselessPushPull
	LEAX	_ship+4,PCR	member energy of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/planet.c:332: assignment: =
	LDD	-6,U		variable `v', declared at core/planet.c:296
	PSHS	B,A
* Line core/planet.c:332: function call: trek_rand_n16()
	LDD	#$012C		decimal 300 signed
	PSHS	B,A		argument 1 of trek_rand_n16(): int
	LBSR	_trek_rand_n16
	LEAS	2,S
	ADDD	#$012C		optim: pushDLoadAdd
* 
* 
	PULS	X
	LBSR	MUL16
	STD	-4,U
* Line core/planet.c:333: if
* LDD #$09C4 optim: optimizeStackOperations1
* PSHS B,A optim: optimizeStackOperations1
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	_ship+8,PCR	member shields of AnonStruct_core/trek.h:694, via variable ship
	ADDD	-4,U		optim: optimizeStackOperations4
	CMPD	#2500		optim: optimizeStackOperations1
	BLS	L00270		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00269 removed
* Line core/planet.c:333
* Line core/planet.c:333: assignment: =
	LDD	#$09C4		decimal 2500 signed
* optim: stripUselessPushPull
* optim: optimizeLeax
* optim: stripUselessPushPull
	STD	_ship+8,PCR	optim: optimizeLeax
	BRA	L00271		jump over else clause
L00270	EQU	*		else clause of if() started at core/planet.c:333
* Line core/planet.c:334
* Line core/planet.c:334: assignment: =
* optim: optimizeStackOperations4
* optim: optimizeStackOperations4
	LDD	_ship+8,PCR	member shields of AnonStruct_core/trek.h:694, via variable ship
	ADDD	-4,U		optim: optimizeStackOperations4
* optim: stripUselessPushPull
* optim: optimizeLeax
* optim: stripUselessPushPull
	STD	_ship+8,PCR	optim: optimizeLeax
L00271	EQU	*		end of if() started at core/planet.c:333
	LDB	#2
* optim: branchToNextLocation
L00084	EQU	*		end of trek_use_energium()
	LEAS	,U
	PULS	U,PC
* END FUNCTION trek_use_energium(): defined at core/planet.c:294
funcend_trek_use_energium	EQU *
funcsize_trek_use_energium	EQU	funcend_trek_use_energium-_trek_use_energium


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.
* Line core/planet.c:12: init of variable planet_name
	LEAX	S00085,PCR	"ANDROMEDA"
	STX	_planet_name+0,PCR	offset in variable planet_name
	LEAX	S00086,PCR	"CETI ALPHA"
	STX	_planet_name+2,PCR	offset in variable planet_name
	LEAX	S00087,PCR	"CYGNUS"
	STX	_planet_name+4,PCR	offset in variable planet_name
	LEAX	S00088,PCR	"GALLISTA"
	STX	_planet_name+6,PCR	offset in variable planet_name
	LEAX	S00089,PCR	"GAMMA REGULA"
	STX	_planet_name+8,PCR	offset in variable planet_name
	LEAX	S00090,PCR	"SIGMA"
	STX	_planet_name+10,PCR	offset in variable planet_name
	LEAX	S00091,PCR	"VEGA"
	STX	_planet_name+12,PCR	offset in variable planet_name
	LEAX	S00092,PCR	"XEVIOUS"
	STX	_planet_name+14,PCR	offset in variable planet_name
* Line core/planet.c:19: init of variable item_name
	LEAX	S00093,PCR	"MONGOL ENERGIUM"
	STX	_item_name+0,PCR	offset in variable item_name
	LEAX	S00094,PCR	"PLASMA BOLTS"
	STX	_item_name+2,PCR	offset in variable item_name
	LEAX	S00095,PCR	"PLASMA BOLT SHIELD"
	STX	_item_name+4,PCR	offset in variable item_name
	LEAX	S00096,PCR	"LIFE SUPPORT SUPPLIES"
	STX	_item_name+6,PCR	offset in variable item_name
	LEAX	S00097,PCR	"RAW ENERGIUM"
	STX	_item_name+8,PCR	offset in variable item_name


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*


*******************************************************************************

* STRING LITERALS
S00085	EQU	*
	FCC	"ANDROMEDA"
	FCB	0
S00086	EQU	*
	FCC	"CETI ALPHA"
	FCB	0
S00087	EQU	*
	FCC	"CYGNUS"
	FCB	0
S00088	EQU	*
	FCC	"GALLISTA"
	FCB	0
S00089	EQU	*
	FCC	"GAMMA REGULA"
	FCB	0
S00090	EQU	*
	FCC	"SIGMA"
	FCB	0
S00091	EQU	*
	FCC	"VEGA"
	FCB	0
S00092	EQU	*
	FCC	"XEVIOUS"
	FCB	0
S00093	EQU	*
	FCC	"MONGOL ENERGIUM"
	FCB	0
S00094	EQU	*
	FCC	"PLASMA BOLTS"
	FCB	0
S00095	EQU	*
	FCC	"PLASMA BOLT SHIELD"
	FCB	0
S00096	EQU	*
	FCC	"LIFE SUPPORT SUPPLIES"
	FCB	0
S00097	EQU	*
	FCC	"RAW ENERGIUM"
	FCB	0
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES
_planet_class_letter	EQU	*		planet_class_letter: const char[]
* Element 0 of array, of type const char
	FCB	$4D		decimal 77
* Element 1 of array, of type const char
	FCB	$4E		decimal 78
* Element 2 of array, of type const char
	FCB	$4F		decimal 79


	ENDSECTION




	SECTION	rwdata


* Statically-initialized global variables
* Statically-initialized local static variables


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
_planets	EQU	*
	RMB	95		planets: struct AnonStruct_core/planet.h:231[]: core/planet.c:6
_planet_count	EQU	*
	RMB	1		planet_count: unsigned char: core/planet.c:7
_inventory	EQU	*
	RMB	5		inventory: unsigned char[]: core/planet.c:8
_planet_evac_end	EQU	*
	RMB	2		planet_evac_end: unsigned int: core/planet.c:9
_planet_name	EQU	*
	RMB	16		planet_name: const char * const[]: core/planet.c:12
_item_name	EQU	*
	RMB	10		item_name: const char * const[]: core/planet.c:19
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 8 utility routine(s).
MUL16	IMPORT
_trek_advance_time	IMPORT
_trek_free_sector	IMPORT
_trek_rand_n	IMPORT
_trek_rand_n16	IMPORT
_trek_shuttle_ok	IMPORT
_trek_transporter_ok	IMPORT
shiftLeft	IMPORT


*******************************************************************************

	END
