* 6809 assembly program generated by cmoc 0.1.86


	SECTION	code


_enemy_hp	IMPORT
_gal_commander	IMPORT
_tractored	IMPORT
_nova_quad	IMPORT
_nova_kills	IMPORT
_gal_enemies	IMPORT
_gal_base	IMPORT
_gal_stars	IMPORT
_gal_known	IMPORT
_gal_nova	IMPORT
_gal_star_gone	IMPORT
_sector	IMPORT
_ship	IMPORT
_hole_threw	IMPORT
_pod_alive	IMPORT
_plasma_shield	IMPORT
_bolt_cell	IMPORT
_bolt_quad	IMPORT
_hail_quad	IMPORT
_warp_hurt	IMPORT
_laser_overheated	IMPORT
_base_under_attack	IMPORT
_bases_lost	IMPORT
_trek_block_y	IMPORT
_trek_block_x	IMPORT
_planet_name	IMPORT
_planet_class_letter	IMPORT
_planets	IMPORT
_planet_count	IMPORT
_item_name	IMPORT
_inventory	IMPORT
_planet_evac_end	IMPORT
_ovl_load	IMPORT
_planet_distress_here	IMPORT
_planet_here	IMPORT
_planet_new	IMPORT
_planet_place	IMPORT
_planet_quadrant_lost	IMPORT
_planet_settlement_lost	IMPORT
_trek_advance	IMPORT
_trek_advance_time	IMPORT
_trek_autonav_ok	IMPORT
_trek_bearing	IMPORT
_trek_capture_supplies	IMPORT
_trek_combat_damage	IMPORT
_trek_dist	IMPORT
_trek_divert	IMPORT
_trek_dock	IMPORT
_trek_docked_safe	IMPORT
_trek_enemy_full_hp	IMPORT
_trek_enemy_turn	IMPORT
_trek_energium_allowed	IMPORT
_trek_enter_quadrant	IMPORT
_trek_events_due	IMPORT
_trek_fire_laser	IMPORT
_trek_fire_ray	IMPORT
_trek_fire_torpedo	IMPORT
_trek_free_sector	IMPORT
_trek_game_state	IMPORT
_trek_hail	IMPORT
_trek_impulse_ok	IMPORT
_trek_is_scheduled	IMPORT
_trek_land	IMPORT
_trek_laser_begin_volley	IMPORT
_trek_laser_damage	IMPORT
_trek_laser_eff	IMPORT
_trek_leave_orbit	IMPORT
_trek_life_replenish	IMPORT
_trek_lrscan_level	IMPORT
_trek_max_warp	IMPORT
_trek_move_delta	IMPORT
_trek_move_impulse	IMPORT
_trek_move_warp	IMPORT
_trek_new_game	IMPORT
_trek_orbit	IMPORT
_trek_plasma_bolt	IMPORT
_trek_rand	IMPORT
_trek_rand_n	IMPORT
_trek_rand_n16	IMPORT
_trek_rng_restore	IMPORT
_trek_rng_state	IMPORT
_trek_run_events	IMPORT
_trek_sched_deviate	IMPORT
_trek_sched_restore	IMPORT
_trek_schedule	IMPORT
_trek_scheduled	IMPORT
_trek_score	IMPORT
_trek_score_sheet	IMPORT
_trek_self_destruct	IMPORT
_trek_set_warp	IMPORT
_trek_shields_down	IMPORT
_trek_shields_up	IMPORT
_trek_shuttle_ok	IMPORT
_trek_srand	IMPORT
_trek_srscan_level	IMPORT
_trek_star_gone	IMPORT
_trek_take_hit	IMPORT
_trek_transporter_ok	IMPORT
_trek_tubes_available	IMPORT
_trek_turn_end	IMPORT
_trek_undock	IMPORT
_trek_unschedule	IMPORT
_trek_use_energium	IMPORT
_trek_wreck_system	IMPORT


*******************************************************************************

* FUNCTION put8(): defined at core/serial.c:14
_put8	EQU	*
.static.function.put8	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
* Formal parameter(s):
*      5,U:    1 byte : v: unsigned char: line 14
* Line core/serial.c:14: assignment: =
	LDB	5,U		variable `v', declared at core/serial.c:14
	PSHS	B
	LDD	_pos+0,PCR	variable `pos', declared at core/serial.c:14
	ADDD	#1
	STD	_pos+0,PCR
	SUBD	#1		post increment yields initial value
	LDX	_out+0,PCR	pointer out
	LEAX	D,X		add offset
	LDB	,S+
	STB	,X
* Useless label L00075 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION put8(): defined at core/serial.c:14
funcend_put8	EQU *
funcsize_put8	EQU	funcend_put8-_put8


*******************************************************************************

* FUNCTION put16(): defined at core/serial.c:17
_put16	EQU	*
.static.function.put16	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
* Formal parameter(s):
*      4,U:    2 bytes: v: unsigned int: line 17
* Line core/serial.c:18: assignment: =
	LDD	4,U		variable v
	CLRA			optim: andA_B0
* optim: stripUselessBitwiseOp
* Cast from `unsigned int' to byte: result already in B
	PSHS	B
	LDD	_pos+0,PCR	variable `pos', declared at core/serial.c:18
	ADDD	#1
	STD	_pos+0,PCR
	SUBD	#1		post increment yields initial value
	LDX	_out+0,PCR	pointer out
	LEAX	D,X		add offset
	LDB	,S+
	STB	,X
* Line core/serial.c:19: assignment: =
	LDD	4,U		variable `v', declared at core/serial.c:17
	TFR	A,B		shift D 8 bits right
	CLRA			unsigned
* Cast from `unsigned int' to byte: result already in B
	PSHS	B
	LDD	_pos+0,PCR	variable `pos', declared at core/serial.c:19
	ADDD	#1
	STD	_pos+0,PCR
	SUBD	#1		post increment yields initial value
	LDX	_out+0,PCR	pointer out
	LEAX	D,X		add offset
	LDB	,S+
	STB	,X
* Useless label L00076 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION put16(): defined at core/serial.c:17
funcend_put16	EQU *
funcsize_put16	EQU	funcend_put16-_put16


*******************************************************************************

* FUNCTION get8(): defined at core/serial.c:22
_get8	EQU	*
.static.function.get8	EQU	*
* Calling convention: Default
* Line core/serial.c:22: return with value
	LDD	_pos+0,PCR	variable `pos', declared at core/serial.c:22
	ADDD	#1
	STD	_pos+0,PCR
	SUBD	#1		post increment yields initial value
	LDX	_in+0,PCR	pointer in
* optimizeLoadDX
	LDB	D,X		get r-value
* Cast from `const unsigned char' to byte: result already in B
* optim: branchToNextLocation
* Useless label L00077 removed
	RTS
* END FUNCTION get8(): defined at core/serial.c:22
funcend_get8	EQU *
funcsize_get8	EQU	funcend_get8-_get8


*******************************************************************************

* FUNCTION get16(): defined at core/serial.c:26
_get16	EQU	*
.static.function.get16	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-2,S
* Local non-static variable(s):
*     -2,U:    2 bytes: lo: unsigned int: line 27
* Line core/serial.c:27: init of variable lo
	LDD	_pos+0,PCR	variable `pos', declared at core/serial.c:27
	ADDD	#1
	STD	_pos+0,PCR
	SUBD	#1		post increment yields initial value
	LDX	_in+0,PCR	pointer in
* optimizeLoadDX
	LDB	D,X		get r-value
	CLRA
	STD	-2,U		variable lo
* Line core/serial.c:28: return with value
	LDD	_pos+0,PCR	variable `pos', declared at core/serial.c:28
	ADDD	#1
	STD	_pos+0,PCR
	SUBD	#1		post increment yields initial value
	LDX	_in+0,PCR	pointer in
* optimizeLoadDX
	LDA	D,X		optim: optimizeLdbTfrClrb
* optim: stripOpToDeadReg
* optim: optimizeLdbTfrClrb
	CLRB
	PSHS	B,A
	LDD	-2,U		variable `lo', declared at core/serial.c:27
	ORA	,S+
	ORB	,S+
* optim: branchToNextLocation
* Useless label L00078 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION get16(): defined at core/serial.c:26
funcend_get16	EQU *
funcsize_get16	EQU	funcend_get16-_get16


*******************************************************************************

* FUNCTION put_bits(): defined at core/serial.c:111
_put_bits	EQU	*
.static.function.put_bits	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-3,S
* Formal parameter(s):
*      4,U:    2 bytes: a: const unsigned char *: line 111
* Local non-static variable(s):
*     -3,U:    1 byte : k: unsigned char: line 115
*     -2,U:    1 byte : i: unsigned char: line 112
*     -1,U:    1 byte : b: unsigned char: line 112
* Line core/serial.c:113: for init
* Line core/serial.c:113: assignment: =
	CLRB
	STB	-2,U		variable i
	BRA	L00088		jump to for condition
L00087	EQU	*
* Line core/serial.c:113: for body
* Line core/serial.c:114: assignment: =
	CLR	-1,U		variable b
* Line core/serial.c:115: for init
* Line core/serial.c:115: assignment: =
	CLRB
	STB	-3,U		variable k
	BRA	L00092		jump to for condition
L00091	EQU	*
* Line core/serial.c:115: for body
* Line core/serial.c:115: if
	LDB	-2,U		variable i
	ADDB	-3,U		variable k
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
* optim: loadCmpZeroBeqOrBne
	BEQ	L00096		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00095 removed
* Line core/serial.c:115
* Line core/serial.c:115: assignment: |=
	CLRA
	LDB	#$01		decimal 1 unsigned
	PSHS	B,A		left side of shift: used and popped by shiftLeft
	LDB	-3,U		variable `k', declared at core/serial.c:115
* optim: stripExtraClrA_B
	LBSR	shiftLeft
* Cast from `unsigned int' to byte: result already in B
	PSHS	B
	LDB	-1,U
	ORB	,S+
	STB	-1,U
L00096	EQU	*		else clause of if() started at core/serial.c:115
* Useless label L00097 removed
* Useless label L00093 removed
* Line core/serial.c:115: for increment(s)
	INC	-3,U
L00092	EQU	*
* Line core/serial.c:115: for condition
	LDB	-3,U		variable k
	CMPB	#$08
	BLO	L00091
* optim: branchToNextLocation
* Useless label L00094 removed
* Line core/serial.c:116: function call: put8()
	LDB	-1,U		variable `b', declared at core/serial.c:112
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Useless label L00089 removed
* Line core/serial.c:113: for increment(s)
* Line core/serial.c:113: assignment: +=
	LDB	-2,U		variable i
	ADDB	#$08		+= operator at core/serial.c:113
	STB	-2,U
L00088	EQU	*
* Line core/serial.c:113: for condition
	LDB	-2,U		variable i
	CMPB	#$40
	BLO	L00087
* optim: branchToNextLocation
* Useless label L00090 removed
* Useless label L00079 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION put_bits(): defined at core/serial.c:111
funcend_put_bits	EQU *
funcsize_put_bits	EQU	funcend_put_bits-_put_bits


*******************************************************************************

* FUNCTION get_bits(): defined at core/serial.c:119
_get_bits	EQU	*
.static.function.get_bits	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-3,S
* Formal parameter(s):
*      4,U:    2 bytes: a: unsigned char *: line 119
* Local non-static variable(s):
*     -3,U:    1 byte : k: unsigned char: line 123
*     -2,U:    1 byte : i: unsigned char: line 120
*     -1,U:    1 byte : b: unsigned char: line 120
* Line core/serial.c:121: for init
* Line core/serial.c:121: assignment: =
	CLRB
	STB	-2,U		variable i
	BRA	L00099		jump to for condition
L00098	EQU	*
* Line core/serial.c:121: for body
* Line core/serial.c:122: assignment: =
* Line core/serial.c:122: function call: get8()
	LBSR	_get8
	STB	-1,U
* Line core/serial.c:123: for init
* Line core/serial.c:123: assignment: =
	CLRB
	STB	-3,U		variable k
	BRA	L00103		jump to for condition
L00102	EQU	*
* Line core/serial.c:123: for body
* Line core/serial.c:123: assignment: =
	CLRA
	LDB	#$01		decimal 1 signed
	PSHS	B
	LDB	-1,U		variable `b', declared at core/serial.c:120
	PSHS	B		left side of shift: used and popped by shiftByteRightUnsigned
	LDB	-3,U		variable `k', declared at core/serial.c:123
* optim: stripExtraClrA_B
	LBSR	shiftByteRightUnsigned
	ANDB	,S+
	PSHS	B
	LDB	-2,U		variable i
	ADDB	-3,U		variable k
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Useless label L00104 removed
* Line core/serial.c:123: for increment(s)
	INC	-3,U
L00103	EQU	*
* Line core/serial.c:123: for condition
	LDB	-3,U		variable k
	CMPB	#$08
	BLO	L00102
* optim: branchToNextLocation
* Useless label L00105 removed
* Useless label L00100 removed
* Line core/serial.c:121: for increment(s)
* Line core/serial.c:121: assignment: +=
	LDB	-2,U		variable i
	ADDB	#$08		+= operator at core/serial.c:121
	STB	-2,U
L00099	EQU	*
* Line core/serial.c:121: for condition
	LDB	-2,U		variable i
	CMPB	#$40
	BLO	L00098
* optim: branchToNextLocation
* Useless label L00101 removed
* Useless label L00080 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION get_bits(): defined at core/serial.c:119
funcend_get_bits	EQU *
funcsize_get_bits	EQU	funcend_get_bits-_get_bits


*******************************************************************************

* FUNCTION put_nib(): defined at core/serial.c:126
_put_nib	EQU	*
.static.function.put_nib	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-1,S
* Formal parameter(s):
*      4,U:    2 bytes: a: const unsigned char *: line 126
* Local non-static variable(s):
*     -1,U:    1 byte : i: unsigned char: line 127
* Line core/serial.c:128: for init
* Line core/serial.c:128: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00107		jump to for condition
L00106	EQU	*
* Line core/serial.c:129: for body
* Line core/serial.c:129: function call: put8()
	LDB	-1,U		variable i
	ADDB	#$01		1
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	LSLB
	LSLB
	LSLB
	LSLB
* Cast from `const unsigned char' to byte: result already in B
	PSHS	B
	CLRA
	LDB	#$0F		decimal 15 signed
	PSHS	B
	LDB	-1,U		variable i
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	ANDB	,S+
	ORB	,S+
* optim: stripExtraClrA_B
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Useless label L00108 removed
* Line core/serial.c:128: for increment(s)
* Line core/serial.c:128: assignment: +=
	LDB	-1,U		variable i
	ADDB	#$02		+= operator at core/serial.c:128
	STB	-1,U
L00107	EQU	*
* Line core/serial.c:128: for condition
	LDB	-1,U		variable i
	CMPB	#$40
	BLO	L00106
* optim: branchToNextLocation
* Useless label L00109 removed
* Useless label L00081 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION put_nib(): defined at core/serial.c:126
funcend_put_nib	EQU *
funcsize_put_nib	EQU	funcend_put_nib-_put_nib


*******************************************************************************

* FUNCTION get_nib(): defined at core/serial.c:131
_get_nib	EQU	*
.static.function.get_nib	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-2,S
* Formal parameter(s):
*      4,U:    2 bytes: a: unsigned char *: line 131
* Local non-static variable(s):
*     -2,U:    1 byte : i: unsigned char: line 132
*     -1,U:    1 byte : b: unsigned char: line 132
* Line core/serial.c:133: for init
* Line core/serial.c:133: assignment: =
	CLRB
	STB	-2,U		variable i
	BRA	L00111		jump to for condition
L00110	EQU	*
* Line core/serial.c:133: for body
* Line core/serial.c:134: assignment: =
* Line core/serial.c:134: function call: get8()
	LBSR	_get8
	STB	-1,U
* Line core/serial.c:135: assignment: =
* optim: storeLoad
	ANDB	#$0F
	PSHS	B
	LDB	-2,U		variable i
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Line core/serial.c:136: assignment: =
	LDB	-1,U		variable `b', declared at core/serial.c:132
	LSRB
	LSRB
	LSRB
	LSRB
	PSHS	B
	LDB	-2,U		variable i
	ADDB	#$01		1
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Useless label L00112 removed
* Line core/serial.c:133: for increment(s)
* Line core/serial.c:133: assignment: +=
	LDB	-2,U		variable i
	ADDB	#$02		+= operator at core/serial.c:133
	STB	-2,U
L00111	EQU	*
* Line core/serial.c:133: for condition
	LDB	-2,U		variable i
	CMPB	#$40
	BLO	L00110
* optim: branchToNextLocation
* Useless label L00113 removed
* Useless label L00082 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION get_nib(): defined at core/serial.c:131
funcend_get_nib	EQU *
funcsize_get_nib	EQU	funcend_get_nib-_get_nib


*******************************************************************************

* FUNCTION put_quad(): defined at core/serial.c:139
_put_quad	EQU	*
.static.function.put_quad	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-1,S
* Formal parameter(s):
*      4,U:    2 bytes: a: const unsigned char *: line 139
* Local non-static variable(s):
*     -1,U:    1 byte : i: unsigned char: line 140
* Line core/serial.c:141: for init
* Line core/serial.c:141: assignment: =
	CLRB
	STB	-1,U		variable i
	LBRA	L00115		jump to for condition
L00114	EQU	*
* Line core/serial.c:143: for body
* Line core/serial.c:143: function call: put8()
	CLRA
	LDB	#$03		decimal 3 signed
	PSHS	B
	LDB	-1,U		variable i
	ADDB	#$03		3
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	ANDB	,S+
	LSLB
	LSLB
	LSLB
	LSLB
	LSLB
	LSLB
	PSHS	B
* optim: stripExtraClrA_B
	LDB	#$03		decimal 3 signed
	PSHS	B
	LDB	-1,U		variable i
	ADDB	#$02		2
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	ANDB	,S+
	LSLB
	LSLB
	LSLB
	LSLB
	PSHS	B
* optim: stripExtraClrA_B
	LDB	#$03		decimal 3 signed
	PSHS	B
	LDB	-1,U		variable i
	ADDB	#$01		1
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	ANDB	,S+
	LSLB
	LSLB
	PSHS	B
* optim: stripExtraClrA_B
	LDB	#$03		decimal 3 signed
	PSHS	B
	LDB	-1,U		variable i
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	ANDB	,S+
	ORB	,S+
	ORB	,S+
	ORB	,S+
* optim: stripExtraClrA_B
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Useless label L00116 removed
* Line core/serial.c:141: for increment(s)
* Line core/serial.c:141: assignment: +=
	LDB	-1,U		variable i
	ADDB	#$04		+= operator at core/serial.c:141
	STB	-1,U
L00115	EQU	*
* Line core/serial.c:141: for condition
	LDB	-1,U		variable i
	CMPB	#$40
	LBLO	L00114
* optim: branchToNextLocation
* Useless label L00117 removed
* Useless label L00083 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION put_quad(): defined at core/serial.c:139
funcend_put_quad	EQU *
funcsize_put_quad	EQU	funcend_put_quad-_put_quad


*******************************************************************************

* FUNCTION get_quad(): defined at core/serial.c:145
_get_quad	EQU	*
.static.function.get_quad	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-2,S
* Formal parameter(s):
*      4,U:    2 bytes: a: unsigned char *: line 145
* Local non-static variable(s):
*     -2,U:    1 byte : i: unsigned char: line 146
*     -1,U:    1 byte : b: unsigned char: line 146
* Line core/serial.c:147: for init
* Line core/serial.c:147: assignment: =
	CLRB
	STB	-2,U		variable i
	LBRA	L00119		jump to for condition
L00118	EQU	*
* Line core/serial.c:147: for body
* Line core/serial.c:148: assignment: =
* Line core/serial.c:148: function call: get8()
	LBSR	_get8
	STB	-1,U
* Line core/serial.c:149: assignment: =
* optim: storeLoad
	ANDB	#$03
	PSHS	B
	LDB	-2,U		variable i
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Line core/serial.c:149: assignment: =
	CLRA
* LDB #$03 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-1,U		variable `b', declared at core/serial.c:146
	LSRB
	LSRB
	ANDB	#3		optim: optimizeStackOperations1
	PSHS	B
	LDB	-2,U		variable i
	ADDB	#$01		1
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Line core/serial.c:150: assignment: =
* optim: stripExtraClrA_B
* LDB #$03 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-1,U		variable `b', declared at core/serial.c:146
	LSRB
	LSRB
	LSRB
	LSRB
	ANDB	#3		optim: optimizeStackOperations1
	PSHS	B
	LDB	-2,U		variable i
	ADDB	#$02		2
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Line core/serial.c:150: assignment: =
* optim: stripExtraClrA_B
* LDB #$03 optim: optimizeStackOperations1
* PSHS B optim: optimizeStackOperations1
	LDB	-1,U		variable `b', declared at core/serial.c:146
	LSRB
	LSRB
	LSRB
	LSRB
	LSRB
	LSRB
	ANDB	#3		optim: optimizeStackOperations1
	PSHS	B
	LDB	-2,U		variable i
	ADDB	#$03		3
	LDX	4,U		pointer a
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Useless label L00120 removed
* Line core/serial.c:147: for increment(s)
* Line core/serial.c:147: assignment: +=
	LDB	-2,U		variable i
	ADDB	#$04		+= operator at core/serial.c:147
	STB	-2,U
L00119	EQU	*
* Line core/serial.c:147: for condition
	LDB	-2,U		variable i
	CMPB	#$40
	LBLO	L00118
* optim: branchToNextLocation
* Useless label L00121 removed
* Useless label L00084 removed
	LEAS	,U
	PULS	U,PC
* END FUNCTION get_quad(): defined at core/serial.c:145
funcend_get_quad	EQU *
funcsize_get_quad	EQU	funcend_get_quad-_get_quad
_trek_state_save	EXPORT


*******************************************************************************

* FUNCTION trek_state_save(): defined at core/serial.c:154
_trek_state_save	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-1,S
* Formal parameter(s):
*      4,U:    2 bytes: buf: unsigned char *: line 154
*      6,U:    2 bytes: max: unsigned int: line 154
* Local non-static variable(s):
*     -1,U:    1 byte : i: unsigned char: line 155
* Line core/serial.c:157: if
	LDD	6,U		variable max
	CMPD	#$0259
	BHS	L00123		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00122 removed
* Line core/serial.c:157
* Line core/serial.c:157: return with value
	CLRA
	CLRB
* Emitted no code to cast `int' to `unsigned int'
	LBRA	L00085		return (core/serial.c:157)
L00123	EQU	*		else clause of if() started at core/serial.c:157
* Useless label L00124 removed
* Line core/serial.c:158: assignment: =
* optim: stripConsecutiveLoadsToSameReg
	LDD	4,U
	STD	_out+0,PCR
* Line core/serial.c:159: assignment: =
	CLRA
	CLRB
	STD	_pos+0,PCR
* Line core/serial.c:161: function call: put8()
	LDB	#$45		decimal 69 signed
	SEX			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:161: function call: put8()
	LDB	#$54		decimal 84 signed
	SEX			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:161: function call: put8()
	CLRA
	LDB	#$12		decimal 18 signed
	PSHS	B,A		argument 1 of put8(): int
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:163: function call: put8()
	LDB	_ship+0,PCR	member quad_y of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:163: function call: put8()
	LDB	_ship+1,PCR	member quad_x of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:164: function call: put8()
	LDB	_ship+2,PCR	member sec_y of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:164: function call: put8()
	LDB	_ship+3,PCR	member sec_x of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:165: function call: put16()
	LDD	_ship+4,PCR	member energy of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:165: function call: put16()
	LDD	_ship+6,PCR	member impulse of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:166: function call: put16()
	LDD	_ship+8,PCR	member shields of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:166: function call: put8()
	LDB	_ship+10,PCR	member torps of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:167: function call: put8()
	LDB	_ship+11,PCR	member laser_eff of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:167: function call: put16()
	LDD	_ship+12,PCR	member laser_heat of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:168: function call: put8()
	LDB	_ship+14,PCR	member warp of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:168: function call: put8()
	LDB	_ship+15,PCR	member shields_up of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:169: function call: put16()
	LDD	_ship+16,PCR	member stardate of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:169: function call: put16()
	LDD	_ship+19,PCR	member stardate_end of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:170: function call: put8()
	LDB	_ship+18,PCR	member time_frac of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:171: function call: put8()
	LDB	_ship+21,PCR	member level of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:171: function call: put16()
	LDD	_ship+22,PCR	member enemies_left of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:172: function call: put8()
	LDB	_ship+36,PCR	member repair_focus of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:173: function call: put16()
	LDD	_ship+37,PCR	member killed of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:173: function call: put16()
	LDD	_ship+39,PCR	member killed_cmd of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:174: function call: put16()
	LDD	_ship+41,PCR	member casualties of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:175: function call: put8()
	LDB	_ship+43,PCR	member lost of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:175: function call: put8()
	LDB	_ship+44,PCR	member docked of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:176: function call: put8()
	LDB	_ship+53,PCR	member orbiting of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:176: function call: put16()
	LDD	_ship+54,PCR	member rescues of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:176: function call: put16()
	LDD	_ship+56,PCR	member stars_gone of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:176: function call: put16()
	LDD	_ship+58,PCR	member wear_last of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:176: function call: put8()
	LDB	_ship+60,PCR	member lost_how of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:177: function call: put16()
	LDD	_ship+45,PCR	member life_reserve of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:177: function call: put8()
	LDB	_ship+47,PCR	member life_gone of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:178: function call: put8()
	LDB	_ship+48,PCR	member boarders of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:178: function call: put16()
	LDD	_ship+49,PCR	member board_until of AnonStruct_core/trek.h:694, via variable ship
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:179: function call: put8()
	LDB	_pod_alive+0,PCR	variable `pod_alive', declared at core/trek.h:1525
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:179: function call: put8()
	LDB	_ship+52,PCR	member mutants of AnonStruct_core/trek.h:694, via variable ship
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:180: function call: put8()
	LDB	_bolt_cell+0,PCR	variable `bolt_cell', declared at core/trek.h:1623
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:180: function call: put8()
	LDB	_bolt_quad+0,PCR	variable `bolt_quad', declared at core/trek.h:1624
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:181: for init
* Line core/serial.c:181: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00126		jump to for condition
L00125	EQU	*
* Line core/serial.c:181: for body
* Line core/serial.c:181: function call: put8()
	LDB	-1,U		variable i
	CLRA			extend byte index expression
	PSHS	B,A		preserve array index
	LEAX	_ship+24,PCR	member sys of AnonStruct_core/trek.h:694, via variable ship
	TFR	X,D
	ADDD	,S++		add stacked array index to array address in D
	TFR	D,X		put resulting address in X
	LDB	,X		get r-value
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Useless label L00127 removed
* Line core/serial.c:181: for increment(s)
	INC	-1,U
L00126	EQU	*
* Line core/serial.c:181: for condition
	LDB	-1,U		variable i
	CMPB	#$0C
	BLO	L00125
* optim: branchToNextLocation
* Useless label L00128 removed
* Line core/serial.c:183: for init
* Line core/serial.c:183: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00130		jump to for condition
L00129	EQU	*
* Line core/serial.c:183: for body
* Line core/serial.c:183: function call: put8()
	LDB	-1,U		variable i
	LEAX	_gal_enemies+0,PCR	address of array gal_enemies
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Useless label L00131 removed
* Line core/serial.c:183: for increment(s)
	INC	-1,U
L00130	EQU	*
* Line core/serial.c:183: for condition
	LDB	-1,U		variable i
	CMPB	#$40
	BLO	L00129
* optim: branchToNextLocation
* Useless label L00132 removed
* Line core/serial.c:184: function call: put_quad()
	LEAX	_gal_base+0,PCR	address of array gal_base
	PSHS	X		argument 1 of put_quad(): unsigned char[]
	LBSR	_put_quad
	LEAS	2,S
* Line core/serial.c:185: function call: put_nib()
	LEAX	_gal_stars+0,PCR	address of array gal_stars
	PSHS	X		argument 1 of put_nib(): unsigned char[]
	LBSR	_put_nib
	LEAS	2,S
* Line core/serial.c:186: function call: put_bits()
	LEAX	_gal_known+0,PCR	address of array gal_known
	PSHS	X		argument 1 of put_bits(): unsigned char[]
	LBSR	_put_bits
	LEAS	2,S
* Line core/serial.c:190: for init
* Line core/serial.c:190: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00134		jump to for condition
L00133	EQU	*
* Line core/serial.c:190: for body
* Line core/serial.c:190: function call: put8()
	LDB	-1,U		variable i
	LEAX	_gal_commander+0,PCR	address of array gal_commander
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Useless label L00135 removed
* Line core/serial.c:190: for increment(s)
	INC	-1,U
L00134	EQU	*
* Line core/serial.c:190: for condition
	LDB	-1,U		variable i
	CMPB	#$40
	BLO	L00133
* optim: branchToNextLocation
* Useless label L00136 removed
* Line core/serial.c:191: function call: put_bits()
	LEAX	_gal_nova+0,PCR	address of array gal_nova
	PSHS	X		argument 1 of put_bits(): unsigned char[]
	LBSR	_put_bits
	LEAS	2,S
* Line core/serial.c:195: for init
* Line core/serial.c:195: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00138		jump to for condition
L00137	EQU	*
* Line core/serial.c:195: for body
* Line core/serial.c:195: function call: put8()
	LDB	-1,U		variable i
	LEAX	_gal_star_gone+0,PCR	address of array gal_star_gone
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Useless label L00139 removed
* Line core/serial.c:195: for increment(s)
	INC	-1,U
L00138	EQU	*
* Line core/serial.c:195: for condition
	LDB	-1,U		variable i
	CMPB	#$20
	BLO	L00137
* optim: branchToNextLocation
* Useless label L00140 removed
* Line core/serial.c:196: for init
* Line core/serial.c:196: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00142		jump to for condition
L00141	EQU	*
* Line core/serial.c:196: for body
* Line core/serial.c:196: function call: put8()
	LDB	-1,U		variable i
	LEAX	_sector+0,PCR	address of array sector
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Useless label L00143 removed
* Line core/serial.c:196: for increment(s)
	INC	-1,U
L00142	EQU	*
* Line core/serial.c:196: for condition
	LDB	-1,U		variable i
	CMPB	#$40
	BLO	L00141
* optim: branchToNextLocation
* Useless label L00144 removed
* Line core/serial.c:197: for init
* Line core/serial.c:197: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00146		jump to for condition
L00145	EQU	*
* Line core/serial.c:197: for body
* Line core/serial.c:197: function call: put16()
	LDB	-1,U		variable i
	CLRA			index expression is of byte type
	LSLB
	ROLA
	LEAX	_enemy_hp+0,PCR	address of array enemy_hp
	LEAX	D,X		add offset
	LDD	,X		get r-value
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Useless label L00147 removed
* Line core/serial.c:197: for increment(s)
	INC	-1,U
L00146	EQU	*
* Line core/serial.c:197: for condition
	LDB	-1,U		variable i
	CMPB	#$40
	BLO	L00145
* optim: branchToNextLocation
* Useless label L00148 removed
* Line core/serial.c:203: for init
* Line core/serial.c:203: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00150		jump to for condition
L00149	EQU	*
* Line core/serial.c:203: for body
* Line core/serial.c:203: function call: put16()
* Line core/serial.c:203: function call: trek_scheduled()
	LDB	-1,U		variable `i', declared at core/serial.c:155
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of trek_scheduled(): unsigned char
	LBSR	_trek_scheduled
	LEAS	2,S
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Useless label L00151 removed
* Line core/serial.c:203: for increment(s)
	INC	-1,U
L00150	EQU	*
* Line core/serial.c:203: for condition
	LDB	-1,U		variable i
	CMPB	#$05
	BLO	L00149
* optim: branchToNextLocation
* Useless label L00152 removed
* Line core/serial.c:204: function call: put16()
* Line core/serial.c:204: function call: trek_rng_state()
	LBSR	_trek_rng_state
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:206: function call: put8()
	LDB	_base_under_attack+0,PCR	variable `base_under_attack', declared at core/trek.h:1676
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:207: function call: put8()
	LDB	_hail_quad+0,PCR	variable `hail_quad', declared at core/trek.h:1629
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:208: function call: put8()
	LDB	_bases_lost+0,PCR	variable `bases_lost', declared at core/trek.h:2613
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:214: function call: put8()
	LDB	_planet_count+0,PCR	variable `planet_count', declared at core/planet.h:241
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:215: for init
* Line core/serial.c:215: assignment: =
	CLRB
	STB	-1,U		variable i
	LBRA	L00154		jump to for condition
L00153	EQU	*
* Line core/serial.c:215: for body
* Line core/serial.c:216: function call: put8()
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LDB	,X		member quad of AnonStruct_core/planet.h:231
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:216: function call: put8()
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LDB	1,X		member sec of AnonStruct_core/planet.h:231
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:217: function call: put8()
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LDB	2,X		member cls of AnonStruct_core/planet.h:231
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:218: function call: put8()
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LDB	3,X		member find of AnonStruct_core/planet.h:231
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:218: function call: put8()
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LDB	4,X		member flags of AnonStruct_core/planet.h:231
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Useless label L00155 removed
* Line core/serial.c:215: for increment(s)
	INC	-1,U
L00154	EQU	*
* Line core/serial.c:215: for condition
	LDB	-1,U		variable i
	CMPB	#$13
	LBLO	L00153
* optim: branchToNextLocation
* Useless label L00156 removed
* Line core/serial.c:220: for init
* Line core/serial.c:220: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00158		jump to for condition
L00157	EQU	*
* Line core/serial.c:220: for body
* Line core/serial.c:220: function call: put8()
	LDB	-1,U		variable i
	LEAX	_inventory+0,PCR	address of array inventory
	ABX			add unsigned 8-bit offset
	LDB	,X		get r-value
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Useless label L00159 removed
* Line core/serial.c:220: for increment(s)
	INC	-1,U
L00158	EQU	*
* Line core/serial.c:220: for condition
	LDB	-1,U		variable i
	CMPB	#$05
	BLO	L00157
* optim: branchToNextLocation
* Useless label L00160 removed
* Line core/serial.c:221: function call: put16()
	LDD	_planet_evac_end+0,PCR	variable `planet_evac_end', declared at core/planet.h:496
	PSHS	B,A		argument 1 of put16(): unsigned int
	LBSR	_put16
	LEAS	2,S
* Line core/serial.c:225: function call: put8()
	LDB	_plasma_shield+0,PCR	variable `plasma_shield', declared at core/trek.h:1615
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of put8(): unsigned char
	LBSR	_put8
	LEAS	2,S
* Line core/serial.c:227: return with value
	LDD	_pos+0,PCR	variable `pos', declared at core/serial.c:10
* optim: branchToNextLocation
L00085	EQU	*		end of trek_state_save()
	LEAS	,U
	PULS	U,PC
* END FUNCTION trek_state_save(): defined at core/serial.c:154
funcend_trek_state_save	EQU *
funcsize_trek_state_save	EQU	funcend_trek_state_save-_trek_state_save
_trek_state_load	EXPORT


*******************************************************************************

* FUNCTION trek_state_load(): defined at core/serial.c:230
_trek_state_load	EQU	*
* Calling convention: Default
	PSHS	U
	LEAU	,S
	LEAS	-1,S
* Formal parameter(s):
*      4,U:    2 bytes: buf: const unsigned char *: line 230
*      6,U:    2 bytes: len: unsigned int: line 230
* Local non-static variable(s):
*     -1,U:    1 byte : i: unsigned char: line 231
* Line core/serial.c:236: if
	LDD	6,U		variable len
	CMPD	#$0259
	BHS	L00162		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00161 removed
* Line core/serial.c:236
	CLRB
	LBRA	L00086		return (core/serial.c:236)
L00162	EQU	*		else clause of if() started at core/serial.c:236
* Useless label L00163 removed
* Line core/serial.c:237: if
	LDB	#$45		decimal 69 signed
	SEX			promotion of binary operand
	PSHS	B,A
* optim: optimizeLdx
	LDB	[4,U]		optim: optimizeLdx
	CLRA			promotion of binary operand
	CMPD	,S++
	BNE	L00164
* optim: branchToNextLocation
* Useless label L00166 removed
	LDB	#$54		decimal 84 signed
	SEX			promotion of binary operand
	PSHS	B,A
	LDX	4,U		get pointer value
* optim: optimizeLeax
	LDB	1,X		optim: optimizeLeax
	CLRA			promotion of binary operand
	CMPD	,S++
	BEQ	L00165		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
L00164	EQU	*		then clause of if() started at core/serial.c:237
* Line core/serial.c:237
	CLRB
	LBRA	L00086		return (core/serial.c:237)
L00165	EQU	*		else clause of if() started at core/serial.c:237
* Useless label L00167 removed
* Line core/serial.c:238: if
	CLRA
* optim: removeUselessOps
* PSHS B,A optim: optimizeStackOperations1
	LDX	4,U		get pointer value
* optim: optimizeLeax
	LDB	2,X		optim: optimizeLeax
* optim: stripExtraClrA_B
	CMPD	#18		optim: optimizeStackOperations1
	BEQ	L00169		 (optim: condBranchOverUncondBranch)
* optim: condBranchOverUncondBranch
* Useless label L00168 removed
* Line core/serial.c:238
	CLRB
	LBRA	L00086		return (core/serial.c:238)
L00169	EQU	*		else clause of if() started at core/serial.c:238
* Useless label L00170 removed
* Line core/serial.c:240: assignment: =
* optim: stripConsecutiveLoadsToSameReg
	LDD	4,U
	STD	_in+0,PCR
* Line core/serial.c:241: assignment: =
	CLRA
	LDB	#$03		decimal 3 signed
	STD	_pos+0,PCR
* Line core/serial.c:243: assignment: =
* Line core/serial.c:243: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+0,PCR	member quad_y of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:243: assignment: =
* Line core/serial.c:243: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+1,PCR	member quad_x of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:244: assignment: =
* Line core/serial.c:244: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+2,PCR	member sec_y of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:244: assignment: =
* Line core/serial.c:244: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+3,PCR	member sec_x of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:245: assignment: =
* Line core/serial.c:245: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+4,PCR	member energy of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:245: assignment: =
* Line core/serial.c:245: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+6,PCR	member impulse of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:246: assignment: =
* Line core/serial.c:246: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+8,PCR	member shields of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:246: assignment: =
* Line core/serial.c:246: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+10,PCR	member torps of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:247: assignment: =
* Line core/serial.c:247: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+11,PCR	member laser_eff of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:247: assignment: =
* Line core/serial.c:247: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+12,PCR	member laser_heat of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:248: assignment: =
* Line core/serial.c:248: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+14,PCR	member warp of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:248: assignment: =
* Line core/serial.c:248: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+15,PCR	member shields_up of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:249: assignment: =
* Line core/serial.c:249: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+16,PCR	member stardate of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:249: assignment: =
* Line core/serial.c:249: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+19,PCR	member stardate_end of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:250: assignment: =
* Line core/serial.c:250: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+18,PCR	member time_frac of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:251: assignment: =
* Line core/serial.c:251: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+21,PCR	member level of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:251: assignment: =
* Line core/serial.c:251: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+22,PCR	member enemies_left of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:252: assignment: =
* Line core/serial.c:252: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+36,PCR	member repair_focus of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:253: assignment: =
* Line core/serial.c:253: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+37,PCR	member killed of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:253: assignment: =
* Line core/serial.c:253: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+39,PCR	member killed_cmd of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:254: assignment: =
* Line core/serial.c:254: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+41,PCR	member casualties of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:255: assignment: =
* Line core/serial.c:255: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+43,PCR	member lost of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:255: assignment: =
* Line core/serial.c:255: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+44,PCR	member docked of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:256: assignment: =
* Line core/serial.c:256: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+53,PCR	member orbiting of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:256: assignment: =
* Line core/serial.c:256: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+54,PCR	member rescues of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:256: assignment: =
* Line core/serial.c:256: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+56,PCR	member stars_gone of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:256: assignment: =
* Line core/serial.c:256: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+58,PCR	member wear_last of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:256: assignment: =
* Line core/serial.c:256: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+60,PCR	member lost_how of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:257: assignment: =
* Line core/serial.c:257: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+45,PCR	member life_reserve of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:257: assignment: =
* Line core/serial.c:257: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+47,PCR	member life_gone of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:258: assignment: =
* Line core/serial.c:258: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+48,PCR	member boarders of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:258: assignment: =
* Line core/serial.c:258: function call: get16()
	LBSR	_get16
* optim: stripUselessPushPull
	LEAX	_ship+49,PCR	member board_until of AnonStruct_core/trek.h:694, via variable ship
* optim: stripUselessPushPull
	STD	,X
* Line core/serial.c:259: assignment: =
* Line core/serial.c:259: function call: get8()
	LBSR	_get8
	STB	_pod_alive+0,PCR
* Line core/serial.c:259: assignment: =
* Line core/serial.c:259: function call: get8()
	LBSR	_get8
* optim: stripExtraPushPullB
	LEAX	_ship+52,PCR	member mutants of AnonStruct_core/trek.h:694, via variable ship
* optim: stripExtraPushPullB
	STB	,X
* Line core/serial.c:260: assignment: =
* Line core/serial.c:260: function call: get8()
	LBSR	_get8
	STB	_bolt_cell+0,PCR
* Line core/serial.c:260: assignment: =
* Line core/serial.c:260: function call: get8()
	LBSR	_get8
	STB	_bolt_quad+0,PCR
* Line core/serial.c:261: for init
* Line core/serial.c:261: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00172		jump to for condition
L00171	EQU	*
* Line core/serial.c:261: for body
* Line core/serial.c:261: assignment: =
* Line core/serial.c:261: function call: get8()
	LBSR	_get8
	PSHS	B
	LDB	-1,U		variable i
	CLRA			extend byte index expression
	PSHS	B,A		preserve array index
	LEAX	_ship+24,PCR	member sys of AnonStruct_core/trek.h:694, via variable ship
	TFR	X,D
	ADDD	,S++		add stacked array index to array address in D
	TFR	D,X		put resulting address in X
	LDB	,S+
	STB	,X
* Useless label L00173 removed
* Line core/serial.c:261: for increment(s)
	INC	-1,U
L00172	EQU	*
* Line core/serial.c:261: for condition
	LDB	-1,U		variable i
	CMPB	#$0C
	BLO	L00171
* optim: branchToNextLocation
* Useless label L00174 removed
* Line core/serial.c:263: for init
* Line core/serial.c:263: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00176		jump to for condition
L00175	EQU	*
* Line core/serial.c:263: for body
* Line core/serial.c:263: assignment: =
* Line core/serial.c:263: function call: get8()
	LBSR	_get8
	PSHS	B
	LDB	-1,U		variable i
	LEAX	_gal_enemies+0,PCR	address of array gal_enemies
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Useless label L00177 removed
* Line core/serial.c:263: for increment(s)
	INC	-1,U
L00176	EQU	*
* Line core/serial.c:263: for condition
	LDB	-1,U		variable i
	CMPB	#$40
	BLO	L00175
* optim: branchToNextLocation
* Useless label L00178 removed
* Line core/serial.c:264: function call: get_quad()
	LEAX	_gal_base+0,PCR	address of array gal_base
	PSHS	X		argument 1 of get_quad(): unsigned char[]
	LBSR	_get_quad
	LEAS	2,S
* Line core/serial.c:265: function call: get_nib()
	LEAX	_gal_stars+0,PCR	address of array gal_stars
	PSHS	X		argument 1 of get_nib(): unsigned char[]
	LBSR	_get_nib
	LEAS	2,S
* Line core/serial.c:266: function call: get_bits()
	LEAX	_gal_known+0,PCR	address of array gal_known
	PSHS	X		argument 1 of get_bits(): unsigned char[]
	LBSR	_get_bits
	LEAS	2,S
* Line core/serial.c:267: for init
* Line core/serial.c:267: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00180		jump to for condition
L00179	EQU	*
* Line core/serial.c:267: for body
* Line core/serial.c:267: assignment: =
* Line core/serial.c:267: function call: get8()
	LBSR	_get8
	PSHS	B
	LDB	-1,U		variable i
	LEAX	_gal_commander+0,PCR	address of array gal_commander
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Useless label L00181 removed
* Line core/serial.c:267: for increment(s)
	INC	-1,U
L00180	EQU	*
* Line core/serial.c:267: for condition
	LDB	-1,U		variable i
	CMPB	#$40
	BLO	L00179
* optim: branchToNextLocation
* Useless label L00182 removed
* Line core/serial.c:268: function call: get_bits()
	LEAX	_gal_nova+0,PCR	address of array gal_nova
	PSHS	X		argument 1 of get_bits(): unsigned char[]
	LBSR	_get_bits
	LEAS	2,S
* Line core/serial.c:269: for init
* Line core/serial.c:269: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00184		jump to for condition
L00183	EQU	*
* Line core/serial.c:269: for body
* Line core/serial.c:269: assignment: =
* Line core/serial.c:269: function call: get8()
	LBSR	_get8
	PSHS	B
	LDB	-1,U		variable i
	LEAX	_gal_star_gone+0,PCR	address of array gal_star_gone
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Useless label L00185 removed
* Line core/serial.c:269: for increment(s)
	INC	-1,U
L00184	EQU	*
* Line core/serial.c:269: for condition
	LDB	-1,U		variable i
	CMPB	#$20
	BLO	L00183
* optim: branchToNextLocation
* Useless label L00186 removed
* Line core/serial.c:270: for init
* Line core/serial.c:270: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00188		jump to for condition
L00187	EQU	*
* Line core/serial.c:270: for body
* Line core/serial.c:270: assignment: =
* Line core/serial.c:270: function call: get8()
	LBSR	_get8
	PSHS	B
	LDB	-1,U		variable i
	LEAX	_sector+0,PCR	address of array sector
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Useless label L00189 removed
* Line core/serial.c:270: for increment(s)
	INC	-1,U
L00188	EQU	*
* Line core/serial.c:270: for condition
	LDB	-1,U		variable i
	CMPB	#$40
	BLO	L00187
* optim: branchToNextLocation
* Useless label L00190 removed
* Line core/serial.c:271: for init
* Line core/serial.c:271: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00192		jump to for condition
L00191	EQU	*
* Line core/serial.c:271: for body
* Line core/serial.c:271: assignment: =
* Line core/serial.c:271: function call: get16()
	LBSR	_get16
	PSHS	B,A
	LDB	-1,U		variable i
	CLRA			index expression is of byte type
	LSLB
	ROLA
	LEAX	_enemy_hp+0,PCR	address of array enemy_hp
	LEAX	D,X		add offset
	PULS	A,B		retrieve value to store
	STD	,X
* Useless label L00193 removed
* Line core/serial.c:271: for increment(s)
	INC	-1,U
L00192	EQU	*
* Line core/serial.c:271: for condition
	LDB	-1,U		variable i
	CMPB	#$40
	BLO	L00191
* optim: branchToNextLocation
* Useless label L00194 removed
* Line core/serial.c:273: for init
* Line core/serial.c:273: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00196		jump to for condition
L00195	EQU	*
* Line core/serial.c:273: for body
* Line core/serial.c:273: function call: trek_sched_restore()
* Line core/serial.c:273: function call: get16()
	LBSR	_get16
	PSHS	B,A		argument 2 of trek_sched_restore(): unsigned int
	LDB	-1,U		variable `i', declared at core/serial.c:231
	CLRA			promoting byte argument to word
	PSHS	B,A		argument 1 of trek_sched_restore(): unsigned char
	LBSR	_trek_sched_restore
	LEAS	4,S
* Useless label L00197 removed
* Line core/serial.c:273: for increment(s)
	INC	-1,U
L00196	EQU	*
* Line core/serial.c:273: for condition
	LDB	-1,U		variable i
	CMPB	#$05
	BLO	L00195
* optim: branchToNextLocation
* Useless label L00198 removed
* Line core/serial.c:274: function call: trek_rng_restore()
* Line core/serial.c:274: function call: get16()
	LBSR	_get16
	PSHS	B,A		argument 1 of trek_rng_restore(): unsigned int
	LBSR	_trek_rng_restore
	LEAS	2,S
* Line core/serial.c:276: assignment: =
* Line core/serial.c:276: function call: get8()
	LBSR	_get8
	STB	_base_under_attack+0,PCR
* Line core/serial.c:277: assignment: =
* Line core/serial.c:277: function call: get8()
	LBSR	_get8
	STB	_hail_quad+0,PCR
* Line core/serial.c:278: assignment: =
* Line core/serial.c:278: function call: get8()
	LBSR	_get8
	STB	_bases_lost+0,PCR
* Line core/serial.c:280: assignment: =
* Line core/serial.c:280: function call: get8()
	LBSR	_get8
	STB	_planet_count+0,PCR
* Line core/serial.c:281: for init
* Line core/serial.c:281: assignment: =
	CLRB
	STB	-1,U		variable i
	LBRA	L00200		jump to for condition
L00199	EQU	*
* Line core/serial.c:281: for body
* Line core/serial.c:282: assignment: =
* Line core/serial.c:282: function call: get8()
	LBSR	_get8
	PSHS	B
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LDB	,S+
	STB	,X
* Line core/serial.c:282: assignment: =
* Line core/serial.c:282: function call: get8()
	LBSR	_get8
	PSHS	B
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LEAX	1,X		member sec of AnonStruct_core/planet.h:231
	LDB	,S+
	STB	,X
* Line core/serial.c:283: assignment: =
* Line core/serial.c:283: function call: get8()
	LBSR	_get8
	PSHS	B
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LEAX	2,X		member cls of AnonStruct_core/planet.h:231
	LDB	,S+
	STB	,X
* Line core/serial.c:284: assignment: =
* Line core/serial.c:284: function call: get8()
	LBSR	_get8
	PSHS	B
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
	LEAX	3,X		member find of AnonStruct_core/planet.h:231
	LDB	,S+
	STB	,X
* Line core/serial.c:284: assignment: =
* Line core/serial.c:284: function call: get8()
	LBSR	_get8
	PSHS	B
	LDB	-1,U		variable i
* optim: stripOpToDeadReg
	LDA	#5		size of array element
	MUL			get offset in bytes in D
	LEAX	_planets+0,PCR	address of array planets
	LEAX	D,X		add offset
* optim: optimizeLeax
	LDB	,S+
	STB	4,X		optim: optimizeLeax
* Useless label L00201 removed
* Line core/serial.c:281: for increment(s)
	INC	-1,U
L00200	EQU	*
* Line core/serial.c:281: for condition
	LDB	-1,U		variable i
	CMPB	#$13
	LBLO	L00199
* optim: branchToNextLocation
* Useless label L00202 removed
* Line core/serial.c:286: for init
* Line core/serial.c:286: assignment: =
	CLRB
	STB	-1,U		variable i
	BRA	L00204		jump to for condition
L00203	EQU	*
* Line core/serial.c:286: for body
* Line core/serial.c:286: assignment: =
* Line core/serial.c:286: function call: get8()
	LBSR	_get8
	PSHS	B
	LDB	-1,U		variable i
	LEAX	_inventory+0,PCR	address of array inventory
	ABX			add unsigned 8-bit offset
	LDB	,S+
	STB	,X
* Useless label L00205 removed
* Line core/serial.c:286: for increment(s)
	INC	-1,U
L00204	EQU	*
* Line core/serial.c:286: for condition
	LDB	-1,U		variable i
	CMPB	#$05
	BLO	L00203
* optim: branchToNextLocation
* Useless label L00206 removed
* Line core/serial.c:287: assignment: =
* Line core/serial.c:287: function call: get16()
	LBSR	_get16
	STD	_planet_evac_end+0,PCR
* Line core/serial.c:288: assignment: =
* Line core/serial.c:288: function call: get8()
	LBSR	_get8
	STB	_plasma_shield+0,PCR
	LDB	#1
* optim: branchToNextLocation
L00086	EQU	*		end of trek_state_load()
	LEAS	,U
	PULS	U,PC
* END FUNCTION trek_state_load(): defined at core/serial.c:230
funcend_trek_state_load	EQU *
funcsize_trek_state_load	EQU	funcend_trek_state_load-_trek_state_load


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Statically-initialized global variables
* Statically-initialized local static variables


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
_pos	EQU	*
	RMB	2		pos: unsigned int: core/serial.c:10
.global.static.variable.pos	EQU	*
_out	EQU	*
	RMB	2		out: unsigned char *: core/serial.c:11
.global.static.variable.out	EQU	*
_in	EQU	*
	RMB	2		in: const unsigned char *: core/serial.c:12
.global.static.variable.in	EQU	*
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 6 utility routine(s).
_trek_rng_restore	IMPORT
_trek_rng_state	IMPORT
_trek_sched_restore	IMPORT
_trek_scheduled	IMPORT
shiftByteRightUnsigned	IMPORT
shiftLeft	IMPORT


*******************************************************************************

	END
