* 6809 assembly program generated by cmoc 0.1.86


	SECTION	code


_sec_y	EXPORT
_out	EXPORT
_f	EXPORT


*******************************************************************************

* FUNCTION f(): defined at /private/tmp/claude-501/-Users-jhonnaker-claude-code-egatrek/09699526-1054-42ba-ac05-2f1d3a68df57/scratchpad/shift.c:5
_f	EQU	*
* Calling convention: Default
* Line /private/tmp/claude-501/-Users-jhonnaker-claude-code-egatrek/09699526-1054-42ba-ac05-2f1d3a68df57/scratchpad/shift.c:5: assignment: =
	CLRB			shift B 8 or more bits left
	CLRA			cast from byte
	STD	_out+0,PCR
* Useless label L00001 removed
	RTS
* END FUNCTION f(): defined at /private/tmp/claude-501/-Users-jhonnaker-claude-code-egatrek/09699526-1054-42ba-ac05-2f1d3a68df57/scratchpad/shift.c:5
funcend_f	EQU *
funcsize_f	EQU	funcend_f-_f


	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ-ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Statically-initialized global variables
_sec_y	EQU	*		sec_y: unsigned char: /private/tmp/claude-501/-Users-jhonnaker-claude-code-egatrek/09699526-1054-42ba-ac05-2f1d3a68df57/scratchpad/shift.c:3
	FCB	$03		decimal 3
* Statically-initialized local static variables


	ENDSECTION




	SECTION	bss


bss_start	EQU	*
* Uninitialized global variables
_out	EQU	*
	RMB	2		out: int: /private/tmp/claude-501/-Users-jhonnaker-claude-code-egatrek/09699526-1054-42ba-ac05-2f1d3a68df57/scratchpad/shift.c:4
* Uninitialized local static variables
bss_end	EQU	*


	ENDSECTION




*******************************************************************************

* Importing 0 utility routine(s).


*******************************************************************************

	END
