/* GENERATED by tools/gen_strings.py -- do not edit.
   The text itself is in STRINGS.DAT on the game disk; only the
   ids and the offset table are in the binary. */
#ifndef STRDATA_H
#define STRDATA_H

#define STR_COUNT 97

#define S_0      0   /*  C128-VDC PORT  */
#define S_1      1   /* 0 TO ABORT, L FOR LIST: */
#define S_2      2   /* 1 MAIN  2 IMPULSE  3 SHIELDS */
#define S_3      3   /* <RETURN> FOR DEFAULT */
#define S_4      4   /* >>DESTRUCT ABORTED<< */
#define S_5      5   /* >>SELF-DESTRUCT SEQUENCE COMMENCING<< */
#define S_6      6   /* >>WRONG PASSWORD, DESTRUCT ABORTED<< */
#define S_7      7   /* ALREADY UP, CAPTAIN. */
#define S_8      8   /* AND RELEASED AS SHAREWARE IN 1992. */
#define S_9      9   /* AWAITING ORDERS CAPTAIN */
#define S_10    10   /* BASIC IS ON THE 40-COLUMN SCREEN. */
#define S_11    11   /* BLOCKED BY OBJECT */
#define S_12    12   /* CAPTAIN, ALL TUBES ARE DAMAGED! */
#define S_13    13   /* CAPTAIN, PLEASE ENTER SELF-DESTRUCT PASSWORD: */
#define S_14    14   /* CAPTAIN, WE HAVE NO TORPEDOS! */
#define S_15    15   /* CLEAN MISS, SIR! */
#define S_16    16   /* COMMUNICATIONS:  */
#define S_17    17   /* COMPUTER DAMAGED */
#define S_18    18   /* COMPUTER:  */
#define S_19    19   /* COULD NOT SAVE. */
#define S_20    20   /* DEPT. OF SPACE */
#define S_21    21   /* DETAILED EVALUATION */
#define S_22    22   /* DOCKED UNDOCKED */
#define S_23    23   /* DOCKED. ALL STORES FULL. */
#define S_24    24   /* DOCKED. NO STORES HERE. */
#define S_25    25   /* DOCKED. TORPEDOS ONLY. */
#define S_26    26   /* EARTH HEADQUARTERS */
#define S_27    27   /* EGA TREK WAS WRITTEN BY NELS ANDERSON */
#define S_28    28   /* ENERGY TORPEDO CONTROL */
#define S_29    29   /* ENERGY TRANSFER */
#define S_30    30   /* ENGINEERING */
#define S_31    31   /* ENGINEERING:  */
#define S_32    32   /* ENTER SELF-DESTRUCT PASSWORD: */
#define S_33    33   /* FILE NAME, <RETURN> FOR DEFAULT, <ESC> TO ABOR */
#define S_34    34   /* FILE NAME: */
#define S_35    35   /* FOR OUTSTANDING PERFORMANCE, THE FOLLOWING DEP */
#define S_36    36   /* FOR VERIFICATION, ENTER YOUR COMMAND LEVEL (1- */
#define S_37    37   /* FROM (1-3): */
#define S_38    38   /* HALL OF FAME */
#define S_39    39   /* HIT ESC TO ABORT */
#define S_40    40   /* HIT RETURN TO CONTINUE */
#define S_41    41   /* ILLOGICAL, CAPTAIN. */
#define S_42    42   /* IMPULSE ENGINES TOO DAMAGED */
#define S_43    43   /* INOPERATIVE */
#define S_44    44   /* INSUFFICIENT ENERGY, CAPTAIN! */
#define S_45    45   /* INVALID WARP FACTOR */
#define S_46    46   /* LEXINGTON IN QUAD  */
#define S_47    47   /* LONG RANGE SCANNERS INOPERATIVE */
#define S_48    48   /* M W L T D R S E Q C F A SND MSGS SAVE INFO HAI */
#define S_49    49   /* MISSION ENDED, CAPTAIN. */
#define S_50    50   /* MONGOL DESTROYED! */
#define S_51    51   /* NAVIGATION */
#define S_52    52   /* NAVIGATION:  */
#define S_53    53   /* NO BASE ALONGSIDE. */
#define S_54    54   /* NO CONTACT */
#define S_55    55   /* NO ENEMY SHIPS HERE */
#define S_56    56   /* NO SAVED GAME FOUND. */
#define S_57    57   /* NO SUCH LOCATION */
#define S_58    58   /* NUMBER TO FIRE: */
#define S_59    59   /* OFFICERS HAVE BEEN INDUCTED INTO THE HALL OF F */
#define S_60    60   /* PLAY AGAIN? */
#define S_61    61   /* PLEASE ENTER YOUR NAME: */
#define S_62    62   /* PRESS RETURN TO BEGIN */
#define S_63    63   /* PREVIOUS MESSAGES */
#define S_64    64   /* QUAD, SECTOR: */
#define S_65    65   /* QUIT <Y/N>? */
#define S_66    66   /* REPAIR TIME */
#define S_67    67   /* RETURN TO CLOSE */
#define S_68    68   /* SECTOR SECURED. WELL DONE. */
#define S_69    69   /* SELF DESTRUCT */
#define S_70    70   /* SHIELDS ALREADY FULL. */
#define S_71    71   /* SHIELDS DOWN. */
#define S_72    72   /* SHIELDS UP. */
#define S_73    73   /* SPACE=NEXT  RETURN=CLOSE */
#define S_74    74   /* SPEED CAPTAIN? */
#define S_75    75   /* STATE OF REPAIR */
#define S_76    76   /* SYSTEM TO CONCENTRATE REPAIRS ON: */
#define S_77    77   /* THAT IS NOT A SECTOR, CAPTAIN. */
#define S_78    78   /* THAT IS OUR LOCATION */
#define S_79    79   /* THE LEXINGTON IS LOST. */
#define S_80    80   /* THE MONGOL INVASION */
#define S_81    81   /* THIS IS AN INDEPENDENT PORT OF HIS GAME */
#define S_82    82   /* TO THE COMMODORE 128. */
#define S_83    83   /* TOO LITTLE ENERGY */
#define S_84    84   /* TOO LITTLE ENERGY. */
#define S_85    85   /* TORPEDO ABSORBED BY STAR. */
#define S_86    86   /* TRACKING... */
#define S_87    87   /* TRANSFER COMPLETE. */
#define S_88    88   /* TUBES CANNOT FIRE. */
#define S_89    89   /* U.S.S. LEXINGTON */
#define S_90    90   /* UP/DOWN TO SCROLL, ESC TO EXIT */
#define S_91    91   /* WARP SPEED SET */
#define S_92    92   /* WE ARE ALREADY DOCKED. */
#define S_93    93   /* WE ARE LOST, CAPTAIN. */
#define S_94    94   /* WE HAVE NOT GOT IT. */
#define S_95    95   /* WEAPONS CONTROL */
#define S_96    96   /* WELCOME ABOARD CAPTAIN! */

extern const unsigned int str_offset[STR_COUNT];

#endif
