/* GENERATED by tools/gen_strings.py -- do not edit.
   The text itself is in STRINGS.DAT on the game disk; only the
   ids and the offset table are in the binary. */
#ifndef STRDATA_H
#define STRDATA_H

#define STR_COUNT 265

#define S_0      0   /*  C128-VDC PORT  */
#define S_1      1   /* 0 TO ABORT, L FOR LIST: */
#define S_2      2   /* 1 MAIN  2 IMPULSE  3 SHIELDS */
#define S_3      3   /* <RETURN> FOR DEFAULT */
#define S_4      4   /* >>DESTRUCT ABORTED<< */
#define S_5      5   /* >>SELF-DESTRUCT SEQUENCE COMMENCING<< */
#define S_6      6   /* >>WRONG PASSWORD, DESTRUCT ABORTED<< */
#define S_7      7   /* ALREADY UP, CAPTAIN. */
#define S_8      8   /* AND RELEASED AS SHAREWARE IN 1992. */
#define S_9      9   /* AWAITING ORDERS CAPTAIN */
#define S_10    10   /* BASIC IS ON THE 40-COLUMN SCREEN. */
#define S_11    11   /* BLOCKED BY OBJECT */
#define S_12    12   /* CAPTAIN, ALL TUBES ARE DAMAGED! */
#define S_13    13   /* CAPTAIN, PLEASE ENTER SELF-DESTRUCT PASSWORD: */
#define S_14    14   /* CAPTAIN, WE HAVE NO TORPEDOS! */
#define S_15    15   /* CLEAN MISS, SIR! */
#define S_16    16   /* COMMUNICATIONS:  */
#define S_17    17   /* COMPUTER DAMAGED */
#define S_18    18   /* COMPUTER:  */
#define S_19    19   /* COULD NOT SAVE. */
#define S_20    20   /* DEPT. OF SPACE */
#define S_21    21   /* DETAILED EVALUATION */
#define S_22    22   /* DOCKED UNDOCKED */
#define S_23    23   /* DOCKED. ALL STORES FULL. */
#define S_24    24   /* DOCKED. NO STORES HERE. */
#define S_25    25   /* DOCKED. TORPEDOS ONLY. */
#define S_26    26   /* EARTH HEADQUARTERS */
#define S_27    27   /* EGA TREK WAS WRITTEN BY NELS ANDERSON */
#define S_28    28   /* ENERGY TORPEDO CONTROL */
#define S_29    29   /* ENERGY TRANSFER */
#define S_30    30   /* ENGINEERING */
#define S_31    31   /* ENGINEERING:  */
#define S_32    32   /* ENTER SELF-DESTRUCT PASSWORD: */
#define S_33    33   /* FILE NAME, <RETURN> FOR DEFAULT, <ESC> TO ABOR */
#define S_34    34   /* FILE NAME: */
#define S_35    35   /* FOR OUTSTANDING PERFORMANCE, THE FOLLOWING DEP */
#define S_36    36   /* FOR VERIFICATION, ENTER YOUR COMMAND LEVEL (1- */
#define S_37    37   /* FROM (1-3): */
#define S_38    38   /* HALL OF FAME */
#define S_39    39   /* HIT ESC TO ABORT */
#define S_40    40   /* HIT RETURN TO CONTINUE */
#define S_41    41   /* ILLOGICAL, CAPTAIN. */
#define S_42    42   /* IMPULSE ENGINES DAMAGED */
#define S_43    43   /* INOPERATIVE */
#define S_44    44   /* INSUFFICIENT ENERGY, CAPTAIN! */
#define S_45    45   /* INVALID WARP FACTOR */
#define S_46    46   /* LEXINGTON IN QUAD  */
#define S_47    47   /* LONG RANGE SCANNERS INOPERATIVE */
#define S_48    48   /* NO SUCH ORDER */
#define S_49    49   /* MISSION ENDED, CAPTAIN. */
#define S_50    50   /* MONGOL DESTROYED! */
#define S_51    51   /* NAVIGATION */
#define S_52    52   /* NAVIGATION:  */
#define S_53    53   /* NOT ADJACENT TO PLANET. */
#define S_54    54   /* NO CONTACT */
#define S_55    55   /* NO ENEMY SHIPS HERE */
#define S_56    56   /* NO SAVED GAME FOUND. */
#define S_57    57   /* NO SUCH LOCATION */
#define S_58    58   /* NUMBER TO FIRE: */
#define S_59    59   /* OFFICERS HAVE BEEN INDUCTED INTO THE HALL OF F */
#define S_60    60   /* PLAY AGAIN? */
#define S_61    61   /* PLEASE ENTER YOUR NAME: */
#define S_62    62   /* PRESS RETURN TO BEGIN */
#define S_63    63   /* PREVIOUS MESSAGES */
#define S_64    64   /* QUAD, SECTOR: */
#define S_65    65   /* QUIT <Y/N>? */
#define S_66    66   /* REPAIR TIME */
#define S_67    67   /* RETURN TO CLOSE */
#define S_68    68   /* SECTOR SECURED. WELL DONE. */
#define S_69    69   /* SELF DESTRUCT */
#define S_70    70   /* SHIELDS ALREADY FULL. */
#define S_71    71   /* SHIELDS DOWN. */
#define S_72    72   /* SHIELDS UP. */
#define S_73    73   /* SPACE=NEXT  RETURN=CLOSE */
#define S_74    74   /* SPEED CAPTAIN? */
#define S_75    75   /* STATE OF REPAIR */
#define S_76    76   /* SYSTEM TO CONCENTRATE REPAIRS ON: */
#define S_77    77   /* THAT IS NOT A SECTOR, CAPTAIN. */
#define S_78    78   /* THAT IS OUR LOCATION */
#define S_79    79   /* THE LEXINGTON IS LOST. */
#define S_80    80   /* THE MONGOL INVASION */
#define S_81    81   /* THIS IS AN INDEPENDENT PORT OF HIS GAME */
#define S_82    82   /* TO THE COMMODORE 128. */
#define S_83    83   /* TOO LITTLE ENERGY */
#define S_84    84   /* TOO LITTLE ENERGY. */
#define S_85    85   /* TORPEDO ABSORBED BY STAR. */
#define S_86    86   /* TRACKING... */
#define S_87    87   /* TRANSFER COMPLETE. */
#define S_88    88   /* TUBES CANNOT FIRE. */
#define S_89    89   /* U.S.S. LEXINGTON */
#define S_90    90   /* UP/DOWN TO SCROLL, ESC TO EXIT */
#define S_91    91   /* WARP SPEED SET */
#define S_92    92   /* WE ARE ALREADY DOCKED. */
#define S_93    93   /* WE ARE LOST, CAPTAIN. */
#define S_94    94   /* WE HAVE NOT GOT IT. */
#define S_95    95   /* WEAPONS CONTROL */
#define S_96    96   /* WELCOME ABOARD CAPTAIN! */
#define S_97    97   /*  ABSORBED FROM  */
#define S_98    98   /*  DESTROYED */
#define S_99    99   /*  HIT FROM  */
#define S_100  100   /*  MONGOL SHIP(S) DESTROYED. */
#define S_101  101   /*  TUBE WORKS. */
#define S_102  102   /*  TUBES WORK. */
#define S_103  103   /*  UNIT HIT ON  */
#define S_104  104   /*  UNITS LOST */
#define S_105  105   /* AMOUNT TO FIRE AT  */
#define S_106  106   /* BASES HIT @ -200 EACH */
#define S_107  107   /* CAPTAIN, ONLY  */
#define S_108  108   /* CAPTAIN, THERE ARE ONLY  */
#define S_109  109   /* CASUALTIES ON BOARD LEXINGTON */
#define S_110  110   /* COMMANDERS KILLED @ 20 EACH */
#define S_111  111   /* CONCENTRATING ON  */
#define S_112  112   /* DEATH POD  */
#define S_113  113   /* DRAGGED TO QUAD  */
#define S_114  114   /* ENEMY BASES DESTROYED @ 50 EACH */
#define S_115  115   /* KILL/DAY RATIO @ 500 PER DAY */
#define S_116  116   /* MONGOL DAMAGED --  */
#define S_117  117   /* MONGOL NOW AT  */
#define S_118  118   /* MONGOLS KILLED @ 10 EACH */
#define S_119  119   /* PENALTY FOR INCOMPLETE MISSION */
#define S_120  120   /* PENALTY FOR LOSS OF SHIP */
#define S_121  121   /* RESCUES @ 200 EACH */
#define S_122  122   /* SECTOR TO FIRE # */
#define S_123  123   /* STARS DESTROYED @ -5 EACH */
#define S_124  124   /* ENERGYCONVERTER */
#define S_125  125   /* SHIELDS */
#define S_126  126   /* LIFE SUPPORT */
#define S_127  127   /* LASERS */
#define S_128  128   /* ENTORP TUBES */
#define S_129  129   /* WARP ENGINES */
#define S_130  130   /* IMPULSE ENGINE */
#define S_131  131   /* S.R. SCANNER */
#define S_132  132   /* L.R. SCANNER */
#define S_133  133   /* COMPUTER */
#define S_134  134   /* TRANSPORTER */
#define S_135  135   /* SHUTTLECRAFT */
#define S_136  136   /* LT. COMMANDER */
#define S_137  137   /* COMMANDER */
#define S_138  138   /* CAPTAIN */
#define S_139  139   /* COMMODORE */
#define S_140  140   /* ADMIRAL */
#define S_141  141   /* ....######.... */
#define S_142  142   /* ...########... */
#define S_143  143   /* ......##...... */
#define S_144  144   /* ..###########. */
#define S_145  145   /* SHORT RANGE SCAN */
#define S_146  146   /* STATUS */
#define S_147  147   /* CHART OF KNOWN GALAXY */
#define S_148  148   /* COMMAND */
#define S_149  149   /* MAIN VIEWER */
#define S_150  150   /* SYSTEMS STATUS */
#define S_151  151   /* MONGOL COMMANDER */
#define S_152  152   /* MONGOL SCOUT */
#define S_153  153   /* SUPPLY STATION */
#define S_154  154   /* MONGOL BATTLESHIP */
#define S_155  155   /* RESTORE A SAVED GAME (Y/N)? */
#define S_156  156   /* WILL YOU REQUIRE A BRIEFING (Y/N)? */
#define S_157  157   /* SCOUT */
#define S_158  158   /* SUPPLY SHIP */
#define S_159  159   /* MONGOL */
#define S_160  160   /*  HIT TIL  */
#define S_161  161   /*  LEFT. */
#define S_162  162   /*  ON ALL */
#define S_163  163   /*  UNIT HIT */
#define S_164  164   /* AMOUNT: */
#define S_165  165   /* BEARING: */
#define S_166  166   /* COMMS:  */
#define S_167  167   /* DAMAGE:  */
#define S_168  168   /* DONE.  */
#define S_169  169   /* ENERGY */
#define S_170  170   /* HELM:  */
#define S_171  171   /* IMPULSE */
#define S_172  172   /* MONGOLS */
#define S_173  173   /* RANGE: */
#define S_174  174   /* RCB-92 */
#define S_175  175   /* SAVE GAME */
#define S_176  176   /* SCANNER:  */
#define S_177  177   /* SCANNERS */
#define S_178  178   /* SCIENCE:  */
#define S_179  179   /* SECTOR: */
#define S_180  180   /* SHIELDS: */
#define S_181  181   /* SOUND OFF */
#define S_182  182   /* SOUND ON */
#define S_183  183   /* STARDATE */
#define S_184  184   /* STARDATE: */
#define S_185  185   /* SYSTEM */
#define S_186  186   /* TO (1-3): */
#define S_187  187   /* WEAPONS:  */
#define S_188  188   /*   1) SHUTTLE CRAFT */
#define S_189  189   /*   2) TRANSPORTER */
#define S_190  190   /*   3) ABORT LANDING */
#define S_191  191   /*  (DAMAGED) */
#define S_192  192   /*  CASUALTIES. */
#define S_193  193   /* , TYPE  */
#define S_194  194   /* ABORTING MISSION. */
#define S_195  195   /* ALLOW SUCH A DANGEROUS PROCEDURE EXCEPT */
#define S_196  196   /* ATTEMPTING TO LOAD ENERGIUM... */
#define S_197  197   /* BARREN */
#define S_198  198   /* CRYSTAL LOADED...IT APPEARS GOOD! */
#define S_199  199   /* DAMAGE TO MAIN ENERGY SYSTEMS. */
#define S_200  200   /* ENERGIUM */
#define S_201  201   /* ENERGIUM SUCCESSFULLY MINED. */
#define S_202  202   /* ENERGY LEVELS INCREASING... */
#define S_203  203   /* ENGINEERING: CAPTAIN, I WISH TO REMIND YOU */
#define S_204  204   /* ENTERING STANDARD ORBIT. */
#define S_205  205   /* EVACUATING SETTLERS... */
#define S_206  206   /* EXPLORED */
#define S_207  207   /* FIRST OFFICER: CAPTAIN, REGULATIONS DO NOT */
#define S_208  208   /* HOW DO YOU WISH TO GET TO THE PLANET? */
#define S_209  209   /* LANDING PARTY */
#define S_210  210   /* LANDING PARTY ATTACKED...  */
#define S_211  211   /* LANDING PARTY BEAMING UP. */
#define S_212  212   /* LANDING PARTY HAS ARRIVED... */
#define S_213  213   /* LANDING PARTY IS ON PLANET... */
#define S_214  214   /* LANDING PARTY TO TRANSPORTER... */
#define S_215  215   /* LAUNCHING SHUTTLECRAFT... */
#define S_216  216   /* MONGOL STATION */
#define S_217  217   /* NO ENERGY GAIN IS APPARENT. */
#define S_218  218   /* NO PLANETS CHARTED */
#define S_219  219   /* NO USE FOR THAT JUST NOW. */
#define S_220  220   /* NOT ORBITTING A PLANET. */
#define S_221  221   /* NOTHING FOUND. */
#define S_222  222   /* NOTHING HAPPENS. */
#define S_223  223   /* NOTHING LEFT ON THIS PLANET. */
#define S_224  224   /* NOTHING TO USE, CAPTAIN. */
#define S_225  225   /* PLANET LIST */
#define S_226  226   /* PLANET SETTLERS FOUND... */
#define S_227  227   /* PROCEDURE. ARE YOU SURE <Y/N>?  */
#define S_228  228   /* SETTLEMENT */
#define S_229  229   /* SHIELDS UP; CANNOT LAND. */
#define S_230  230   /* SHUTTLECRAFT IS DAMAGED. */
#define S_231  231   /* SHUTTLECRAFT RETURNING. */
#define S_232  232   /* STANDARD ORBIT 301 */
#define S_233  233   /* SYSTEMS GOING UNSTABLE... */
#define S_234  234   /* THAT THIS IS AN EXTREMELY HAZARDOUS */
#define S_235  235   /* THE CRYSTAL APPEARS TO BE DAMAGED. */
#define S_236  236   /* THE TRANSPORTER IS DAMAGED. */
#define S_237  237   /* THIS CRYSTAL IS DEFECTIVE! ENERGY */
#define S_238  238   /* UNDER EXTREME LOW ENERGY CONDITIONS. */
#define S_239  239   /* USE AN ITEM */
#define S_240  240   /* WE ARE ALREADY IN ORBIT. */
#define S_241  241   /* WHICH ITEM DO YOU WISH TO USE? */
#define S_242  242   /* WHICH?  */
#define S_243  243   /* CAPTAIN! THAT WAS A BASE! */
#define S_244  244   /* TORPEDO FAILED TO DETONATE. */
#define S_245  245   /* TORPEDO HIT A PLANET. */
#define S_246  246   /* TORPEDO PASSED WIDE. */
#define S_247  247   /* % EFFICIENCY. */
#define S_248  248   /* LASERS OVERHEAT. NOW AT  */
#define S_249  249   /* CAUGHT IN TRACTOR BEAM. PULLED TO  */
#define S_250  250   /* Life support depleted. */
#define S_251  251   /* ENGINEERING: */
#define S_252  252   /* Not on reserve life support. */
#define S_253  253   /* RESERVE, DAYS */
#define S_254  254   /* Replenishing reserve life support. */
#define S_255  255   /* Boarders hold EnTorp control. */
#define S_256  256   /* Boarders hold engineering. */
#define S_257  257   /* Boarders hold laser control. */
#define S_258  258   /* Boarders in EnTorp control! */
#define S_259  259   /* Boarders in engineering! */
#define S_260  260   /* Boarders in laser control! */
#define S_261  261   /* Boarding party eliminated. */
#define S_262  262   /* SECURITY: */
#define S_263  263   /* COMMUNICATIONS: */
#define S_264  264   /* Supernova  */

extern const unsigned int str_offset[STR_COUNT];

#endif
