/* Video for an Apple IIgs: the console in Super Hi-Res 320 mode.
 *
 * MEASURED BEFORE IT WAS WRITTEN. src/gsprobe.c drew sixteen bands over a
 * sixteen-colour palette on a real ROM 03 and tools/count_colours.py counted
 * SIXTEEN DISTINCT COLOURS off the snapshot -- against the FOUR that 640 mode
 * gives and that ruled this machine out on 2026-09-05. The console needs
 * fifteen. See README.md.
 *
 * 320 x 200 IS 40 x 25 CELLS OF 8 x 8, EXACTLY. No margin, no centring, no
 * rounding: the arithmetic that cost the CoCo 3 card port a MARGIN_Y is
 * simply absent here, which is the one place this machine is easier than the
 * others.
 *
 * THE PALETTE HOLDS EGA'S OWN SIXTEEN, so EGA_TO_VDC is the identity and
 * BROWN is brown. The C128 maps EGA onto a fixed RGBI chip with a 4-bit
 * rotate and loses exactly one colour; the MEGA65 writes EGA's values into a
 * programmable palette and loses none. This is the MEGA65's answer, and the
 * levels make it free: EGA's two-bits-per-gun values are $00/$55/$AA/$FF,
 * every one a duplicated nibble, so the IIgs's four-bit guns take the high
 * nibble and the colour is exact rather than approximated.
 *
 * THE FONT IS THE PROJECT'S OWN. coco3/src/font6x8.h is generated by
 * coco3/tools/gen_font.py from artwork authored in this repository -- not
 * lifted from anyone's character ROM, which matters here because a IIgs's
 * Mega II character generator is not CPU-readable anyway. Six significant
 * columns go into an eight-pixel cell shifted left by one, so every glyph
 * gets a blank column either side and the text breathes.
 *
 * THE BOX GLYPHS CANNOT BE SHIFTED, THEY HAVE TO CONNECT. A horizontal rule
 * that is six pixels wide in an eight-pixel cell draws a dashed line across
 * the console. So codes 64..127 are authored at eight wide below, by the
 * mechanical widening of the six-wide set that the comment there sets out.
 *
 * EVERY WRITE IS LONG ADDRESSING. SHR lives at $E1/2000 and llvm-mos's code
 * generator never emits a 24-bit store on its own, so the innermost loop here
 * is `sta [dp],y` in hand-written assembly. That is the port's central seam
 * and the first thing that was proved on the machine.
 */
#include "../../c128/src/vdc.h"
#include "../../core/ega.h"
#include "../../c128/src/egavdc.h"   /* EGA_TO_VDC -- the identity here, see below */
#include "../../coco3/src/font6x8.h"

#define ASMVAR __attribute__((used, retain))

#define NEWVIDEO (*(volatile unsigned char *)0xC029)

#define COLS 40
#define ROWS 25
#define ROW_BYTES 160          /* 320 pixels at two per byte */
#define CELL_BYTES 4           /* eight pixels */
#define CELL_H 8

#define SHR_PIX  0x2000        /* all three in bank $E1 */
#define SHR_SCB  0x9D00
#define SHR_PAL  0x9E00

/* ---------------------------------------------------------------- the seam */

/* A 24-bit pointer in direct page: `sta [dp],y` is the only store on this CPU
   that reaches another bank AND takes an index. `used, retain` because a
   symbol only inline assembly names is invisible to LTO and gets dropped --
   the failure is `undefined symbol` at link time from a file that compiled
   clean. */
ASMVAR __attribute__((section(".zp.bss"))) unsigned char gs_p[3];
ASMVAR unsigned char gs_cell[CELL_BYTES];
ASMVAR unsigned char gs_alo, gs_ahi, gs_val, gs_n;

/* Store gs_cell[0..3] at $E1/gs_ahi:gs_alo.
   OPERANDS AS GLOBALS, NEVER AS REGISTER CONSTRAINTS. The first probe in this
   port passed them as `"a"(lo), "x"(hi)` while the compiler was keeping a loop
   counter in A across the call; the asm destroyed A and the loop ran forever
   with the counter stuck at 1. An input the asm overwrites must be declared,
   and the reliable way not to get that wrong is to take nothing in a
   register. */
static void put_cell_row(void)
{
    __asm__ volatile(
        "lda gs_alo\n\t"  "sta gs_p+0\n\t"
        "lda gs_ahi\n\t"  "sta gs_p+1\n\t"
        "lda #$e1\n\t"    "sta gs_p+2\n\t"
        "ldy #$00\n\t"
        "1:\n\t"
        "lda gs_cell,y\n\t"
        "sta [gs_p],y\n\t"
        "iny\n\t"
        "cpy #4\n\t"
        "bne 1b\n\t"
        : : : "a", "y", "memory");
}

/* Fill gs_n pages from $E1/gs_ahi:00 with gs_val -- the clear. */
static void bankfill(void)
{
    __asm__ volatile(
        "lda #$00\n\t"   "sta gs_p+0\n\t"
        "lda gs_ahi\n\t" "sta gs_p+1\n\t"
        "lda #$e1\n\t"   "sta gs_p+2\n\t"
        "ldx gs_n\n\t"
        "1:\n\t" "ldy #$00\n\t" "lda gs_val\n\t"
        "2:\n\t" "sta [gs_p],y\n\t" "iny\n\t" "bne 2b\n\t"
        "inc gs_p+1\n\t" "dex\n\t" "bne 1b\n\t"
        : : : "a", "x", "y", "memory");
}

static void poke_e1(unsigned int addr, unsigned char v)
{
    gs_alo = (unsigned char)(addr & 0xFF);
    gs_ahi = (unsigned char)(addr >> 8);
    gs_cell[0] = v;
    __asm__ volatile(
        "lda gs_alo\n\t"  "sta gs_p+0\n\t"
        "lda gs_ahi\n\t"  "sta gs_p+1\n\t"
        "lda #$e1\n\t"    "sta gs_p+2\n\t"
        "ldy #$00\n\t"
        "lda gs_cell\n\t" "sta [gs_p],y\n\t"
        : : : "a", "y", "memory");
}

/* --------------------------------------------------------------- the glyphs */

/* CODES 64..127 AT EIGHT PIXELS WIDE. The six-wide set in font6x8.h is
   widened by one rule, applied by hand here rather than at runtime so that
   what ships is what was looked at:

       $3F  all six columns   -> $FF  all eight      (rules must CONNECT)
       $0C  the middle two    -> $18  the middle two
       $0F  middle to right   -> $1F  middle to right
       $3C  left to middle    -> $F8  left to middle
       $1E  columns 1..4      -> $3C  columns 2..5   (the badge disc)

   A rule glyph goes to the full eight; a stem stays two wide and centred. Any
   other treatment leaves a gap at a cell boundary, and the console is drawn
   almost entirely out of these. */
typedef struct { unsigned char code; unsigned char row[CELL_H]; } GsBox;

static const GsBox gs_box[] = {
    { 64, {0x00,0x00,0x00,0xFF,0xFF,0x00,0x00,0x00}},
    { 81, {0x00,0x00,0x3C,0x7E,0x7E,0x3C,0x00,0x00}},
    { 91, {0x18,0x18,0x18,0xFF,0xFF,0x18,0x18,0x18}},
    { 93, {0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x18}},
    { 98, {0x00,0x00,0x00,0x00,0xFF,0xFF,0xFF,0xFF}},
    {100, {0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xFF}},
    {107, {0x18,0x18,0x18,0x1F,0x1F,0x18,0x18,0x18}},
    {109, {0x18,0x18,0x18,0x1F,0x1F,0x00,0x00,0x00}},
    {110, {0x00,0x00,0x00,0xF8,0xF8,0x18,0x18,0x18}},
    {112, {0x00,0x00,0x00,0x1F,0x1F,0x18,0x18,0x18}},
    {113, {0x18,0x18,0x18,0xFF,0xFF,0x00,0x00,0x00}},
    {114, {0x00,0x00,0x00,0xFF,0xFF,0x18,0x18,0x18}},
    {115, {0x18,0x18,0x18,0xF8,0xF8,0x18,0x18,0x18}},
    {125, {0x18,0x18,0x18,0xF8,0xF8,0x00,0x00,0x00}},
};
#define GS_BOX_COUNT ((int)(sizeof gs_box / sizeof gs_box[0]))

static void glyph_rows(unsigned char ch, unsigned char *out)
{
    unsigned char base = (unsigned char)(ch & 0x7F);
    unsigned char rev  = (unsigned char)(ch & 0x80);
    int i, j;

    if (base < FONT_CODES) {
        /* Six significant columns, bit 5 leftmost, into an eight-pixel cell
           with a blank column either side. */
        for (j = 0; j < CELL_H; j++)
            out[j] = (unsigned char)(font6x8[base][j] << 1);
    } else {
#ifdef GS_BOX_NAIVE
        /* THE WRONG WAY, KEPT BUILDABLE SO THE GATE CAN BE SHOWN TO CATCH IT.
           Shifting the six-wide box set like the text is the obvious thing to
           do and it draws a rule with a two-pixel gap at every cell boundary
           -- which at this scale reads as a slightly lighter line rather than
           as a defect. tools/check_sheet.py counts the black pixels inside a
           twenty-cell rule; `make sheetfail` builds this variant and proves
           the count is not always zero. */
        for (i = 0; i < FONT_BOX_COUNT; i++)
            if (font_box[i].code == base) {
                for (j = 0; j < CELL_H; j++)
                    out[j] = (unsigned char)(font_box[i].row[j] << 1);
                goto shade;
            }
#else
        for (i = 0; i < GS_BOX_COUNT; i++)
            if (gs_box[i].code == base) {
                for (j = 0; j < CELL_H; j++)
                    out[j] = gs_box[i].row[j];
                goto shade;
            }
#endif
        /* THE MISSING-GLYPH MARKER, LOUD ON PURPOSE. A code with no entry is a
           bug in THIS file, not in the caller, and a blank cell hides it -- on
           the Amiga this marker is what caught two missing bracket glyphs. */
        for (j = 0; j < CELL_H; j++)
            out[j] = (unsigned char)((j == 0 || j == CELL_H - 1) ? 0xFF : 0x81);
    }

shade:
    /* Reverse video is a RULE, not data: 160 (the solid badge body), 226 and
       228 fall out of 32, 98 and 100 rather than being written again. Eight
       bits, because the cell is eight wide -- inverting six would leave two
       black columns down every solid cell. */
    if (rev)
        for (j = 0; j < CELL_H; j++)
            out[j] = (unsigned char)~out[j];
}

/* ------------------------------------------------------------- the palette */

/* EGA's own sixteen. Levels $00/$55/$AA/$FF are duplicated nibbles, so the
   IIgs's four-bit guns take the high nibble and the colour is EXACT. Copied
   from mega65/src/m65vid.c, which made the same argument for the VIC-IV. */
static const unsigned char ega_r[16] = {
    0x0,0x0,0x0,0x0,0xA,0xA,0xA,0xA, 0x5,0x5,0x5,0x5,0xF,0xF,0xF,0xF };
static const unsigned char ega_g[16] = {
    0x0,0x0,0xA,0xA,0x0,0x0,0x5,0xA, 0x5,0x5,0xF,0xF,0x5,0x5,0xF,0xF };
static const unsigned char ega_b[16] = {
    0x0,0xA,0x0,0xA,0x0,0xA,0x0,0xA, 0x5,0xF,0x5,0xF,0x5,0xF,0x5,0xF };

/* ------------------------------------------------- the foreground expansion

   Four bits of glyph become two bytes of screen, and which two depends only
   on the foreground colour -- the background is entry 0, black, everywhere
   except a reverse-video cell, where the GLYPH is inverted rather than the
   colours. So the sixteen possible nibbles are expanded once per colour
   change and reused, which for scr_puts means once per string. */
static unsigned char exp0[16], exp1[16];
static unsigned char exp_fg = 0xFF;

static void set_fg(unsigned char fg)
{
    unsigned char n, a, b;
    if (fg == exp_fg) return;
    exp_fg = fg;
    for (n = 0; n < 16; n++) {
        a = (unsigned char)(((n & 8) ? fg : 0) << 4);
        a |= (unsigned char)((n & 4) ? fg : 0);
        b = (unsigned char)(((n & 2) ? fg : 0) << 4);
        b |= (unsigned char)((n & 1) ? fg : 0);
        exp0[n] = a;
        exp1[n] = b;
    }
}

/* ---------------------------------------------------------------- the calls */

void vdc_init(void)
{
    unsigned int i;

    /* SHR ON FIRST, AND THAT ORDERING IS MEASURED, not taste. Drawing into a
       dark screen and revealing it at the end is the right instinct on every
       other machine here, and three forms of the first probe did exactly that
       and drew nothing. The working 2026-09-05 measurement set $C029 before
       filling anything; so does this. See README.md. */
    NEWVIDEO = 0xC1;

    for (i = 0; i < 200; i++)              /* 320 mode, palette 0, every line */
        poke_e1(SHR_SCB + i, 0x00);

    for (i = 0; i < 16; i++) {             /* $0RGB, little endian */
        poke_e1(SHR_PAL + i * 2,
                (unsigned char)((ega_g[i] << 4) | ega_b[i]));
        poke_e1(SHR_PAL + i * 2 + 1, ega_r[i]);
    }

    exp_fg = 0xFF;                         /* the cache knows nothing yet */
    scr_clear();
}

void vdc_shutdown(void)
{
    NEWVIDEO = 0x01;                       /* SHR off, text back */
}

void plat_exit(void)
{
    /* A PORT THAT HAS TAKEN THE WHOLE MACHINE HAS TO SAY HOW IT GIVES IT
       BACK. There is no ProDOS to return to and no BASIC worth landing in, so
       this stops with the display restored rather than falling into a runtime
       that assumes a small program in low memory -- which on the C128 BRKed
       into the monitor every single time and shipped that way in v0.9.0. */
    vdc_shutdown();
    for (;;) ;
}

void wait_vsync(void)
{
    /* $C019 bit 7 is VBL. Waiting for the LINE it is not in avoids sitting
       through a whole frame when we are already in the blanking interval. */
    while ((*(volatile unsigned char *)0xC019) & 0x80) ;
    while (!((*(volatile unsigned char *)0xC019) & 0x80)) ;
}

void scr_clear(void)
{
    gs_ahi = (unsigned char)(SHR_PIX >> 8);
    gs_val = 0x00;
    gs_n   = 125;                           /* 200 rows of 160 bytes, exactly */
    bankfill();
}

void scr_put(unsigned char x, unsigned char y, unsigned char ch,
             unsigned char color)
{
    unsigned char rows[CELL_H];
    unsigned int addr;
    unsigned char r, bits;

    if (x >= COLS || y >= ROWS) return;

    set_fg((unsigned char)(EGA_TO_VDC(color) & 0x0F));
    glyph_rows(ch, rows);

    addr = SHR_PIX + (unsigned int)y * (CELL_H * ROW_BYTES)
                   + (unsigned int)x * CELL_BYTES;

    for (r = 0; r < CELL_H; r++) {
        bits = rows[r];
        gs_cell[0] = exp0[bits >> 4];
        gs_cell[1] = exp1[bits >> 4];
        gs_cell[2] = exp0[bits & 0x0F];
        gs_cell[3] = exp1[bits & 0x0F];
        gs_alo = (unsigned char)(addr & 0xFF);
        gs_ahi = (unsigned char)(addr >> 8);
        put_cell_row();
        addr += ROW_BYTES;
    }
}

/* NOTE the split, which vdc.h states and this file must honour: scr_puts
   takes ASCII and converts; every other routine takes a RAW screen code. The
   box-drawing glyphs sit at 64..127, which is precisely the range the ASCII
   converter rewrites, so panel borders must not go through it. */
void scr_puts(unsigned char x, unsigned char y, const char *s,
              unsigned char color)
{
    while (*s && x < COLS) {
        unsigned char u = (unsigned char)*s++;
        unsigned char c;

        if (u >= 32 && u <= 63)       c = u;
        else if (u >= 64 && u <= 95)  c = (unsigned char)(u - 64);
        else if (u >= 97 && u <= 122) c = (unsigned char)(u - 96);
        else                          c = 32;

        scr_put(x, y, c, color);
        x++;
    }
}

void scr_hline(unsigned char x, unsigned char y, unsigned char w,
               unsigned char ch, unsigned char color)
{
    while (w--) scr_put(x++, y, ch, color);
}

void scr_vline(unsigned char x, unsigned char y, unsigned char h,
               unsigned char ch, unsigned char color)
{
    while (h--) scr_put(x, y++, ch, color);
}

void scr_fill_rect(unsigned char x, unsigned char y, unsigned char w,
                   unsigned char h, unsigned char ch, unsigned char color)
{
    unsigned char j;
    for (j = 0; j < h; j++) scr_hline(x, (unsigned char)(y + j), w, ch, color);
}
