/* GENERATED by tools/make_music.py -- do not edit.
   The music is this port's own; see that file. */
#ifndef MUSIC_DATA_H
#define MUSIC_DATA_H

#define MUSIC_PRESENT 1

#define MUS_TITLE  0   /* title screen, 106 notes */
#define MUS_END    1   /* end of game, 78 notes */
#define SFX_A      2   /* lasers fire, 2 notes */
#define SFX_B      3   /* torpedo launch, 6 notes */
#define SFX_C      4   /* status goes to ALERT, 2 notes */
#define SFX_D      5   /* Vandal Death Pod enters the quadrant, 2 notes */
#define SFX_E      6   /* incoming Mongol fire, 3 notes */

#define MUS_COUNT 7

/* Byte offset of each track inside MUSIC.DAT. */
extern const unsigned int mus_offset[MUS_COUNT];

#endif
