#!/usr/bin/env python3
"""Generate c128/src/music_data.h from the original executable.

NOTHING THIS WRITES IS COMMITTED. EGA Trek's note data is Nels Anderson's
creative work in the same way the message prose is, so the generated header is
gitignored alongside reference/ itself. The repo carries the generator; a
build carries the notes only on a machine that already has the shareware
package.

If reference/EGATREK_unpacked.exe is absent -- which is the normal state of a
fresh clone -- this writes a header with empty tracks instead of failing, so
the port still builds and simply plays nothing. That is deliberate: a build
that breaks without gitignored material is a build nobody else can run.

Format is unchanged from the original: (duration, frequency/10) byte pairs
terminated by a zero duration, with frequency 0 meaning a rest. Keeping the
original's own units means the region scaling stays at runtime, where
sidfreq.h can do it -- see MEASURED.md for why that matters.
"""
import os
import sys

EXE    = "reference/EGATREK_unpacked.exe"
DGROUP = 0x2D820
OUT    = "c128/src/music_data.h"

TRACKS = [
    ("MUS_TITLE", 0x057E, "title screen"),
    ("MUS_END",   0x071A, "end of game"),
    # All five IDENTIFIED 2026-08-22 by resolving the strings each calling
    # routine prints. See MEASURED.md; the routine's own words name it.
    ("SFX_A",     0x099A, "lasers fire"),
    ("SFX_B",     0x09A0, "torpedo launch"),
    ("SFX_C",     0x09AE, "status goes to ALERT"),
    ("SFX_D",     0x09B4, "Vandal Death Pod enters the quadrant"),
    ("SFX_E",     0x09BA, "incoming Mongol fire"),
]


def read_track(data, off, limit=2000):
    p, out = DGROUP + off, []
    while len(out) < limit:
        dur, ten = data[p], data[p + 1]
        p += 2
        if dur == 0:
            break
        out.append((dur, ten))
    return out


def main():
    have = os.path.exists(EXE)
    data = open(EXE, "rb").read() if have else None

    hdr = OUT
    src = OUT[:-2] + ".c"

    tracks = [(name, read_track(data, off) if have else [], what)
              for name, off, what in TRACKS]

    # Ids and one extern in the header; the arrays in their own translation
    # unit. Putting `static const` tables in a header instead cost a kilobyte
    # per includer and cl65 said so -- three "defined but never used" warnings,
    # one for each .c that pulled it in.
    with open(hdr, "w") as f:
        f.write("/* GENERATED by tools/gen_music.py -- do not edit, do not commit.\n"
                "   See that file for why the note data is not in the repository. */\n"
                "#ifndef MUSIC_DATA_H\n#define MUSIC_DATA_H\n\n")
        f.write("#define MUSIC_PRESENT %d\n\n" % (1 if have else 0))
        for i, (name, t, what) in enumerate(tracks):
            f.write("#define %-10s %d   /* %s, %d notes */\n"
                    % (name, i, what, len(t)))
        f.write("\n#define MUS_COUNT %d\n\n" % len(tracks))
        f.write("/* Byte offset of each track inside MUSIC.DAT. */\n")
        f.write("extern const unsigned int mus_offset[MUS_COUNT];\n\n")
        f.write("#endif\n")

    with open(src, "w") as f:
        f.write("/* GENERATED by tools/gen_music.py -- do not edit, do not commit. */\n")
        f.write('#include "music_data.h"\n\n')
        f.write("/* Offsets only. THE NOTES ARE NOT HERE -- they live in MUSIC.DAT\n"
                "   on the game disk and stream into far memory at startup. That is\n"
                "   1,052 bytes out of a 42K address space, and it means a clone\n"
                "   with no reference/ gets no music file rather than a binary with\n"
                "   Anderson's note data compiled in. */\n")
        f.write("const unsigned int mus_offset[MUS_COUNT] = {\n")
        off = 0
        for i, (name, notes, what) in enumerate(tracks):
            f.write("    %5d,   /* %s */\n" % (off, name))
            off += (len(notes) + 1) * 2
        f.write("};\n")

    blob = bytearray()
    for name, notes, what in tracks:
        for d, ten in notes:
            blob.append(d & 0xFF); blob.append(ten & 0xFF)
        blob.append(0); blob.append(0)
    os.makedirs("c128/build", exist_ok=True)
    open("c128/build/music.dat", "wb").write(blob)
    print("gen_music: %d tracks, %d bytes -> build/music.dat" % (len(tracks), len(blob)))

    if have:
        print("gen_music: wrote %s and .c from %s" % (OUT, EXE))
    else:
        print("gen_music: %s absent -- wrote %s and .c with empty tracks"
              % (EXE, OUT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
