/* GENERATED by tools/make_music.py -- do not edit. */
#include "music_data.h"

/* Offsets only. The notes live in MUSIC.DAT on the game disk and
   stream into far memory at startup, which keeps them out of a 42K
   address space. */
const unsigned int mus_offset[MUS_COUNT] = {
        0,   /* MUS_TITLE */
      214,   /* MUS_END */
      372,   /* SFX_A */
      378,   /* SFX_B */
      392,   /* SFX_C */
      398,   /* SFX_D */
      404,   /* SFX_E */
};
